### ISSUE TITLE
自定义订阅填充插件导致我的订阅一直转圈无法打开的问题

### ISSUE THREAD

**Issue by dlovew** [thsrite/MoviePilot-Plugins#102]
![屏幕截图_30-10-2024_233441_192 168 2 3](https://github.com/user-attachments/assets/117eab22-30a5-4389-8e0a-02441055f62a)
只选中了图示的三个选项，订阅剧集成功以后，我的订阅就一直转圈无法打开，稳定复现，并且站点也不生效，看记录站点是生效的，但是订阅详情里又相关站点并不是被选中的状态，下面是出现问题的订阅数据

2024-10-30 23:37:07 | 战国妖狐 | 种子下载自定义配置 | {"resolution": "1080[pi]\|x1080", "sites": "[4]"}

**Comment by thsrite** [comment]
更新2.8.1试试

**Comment by dlovew** [comment]
> > 更新2.8.1试试
> 
> 不好意思，刚得空，初步测试了一下，我还是选中站点、制作组、分辨率，没有问题。其他情况我没有测试，如果有问题我再提issue，感谢

修正：清晰度好像无效，下载的种子1080和2160都有

**Comment by thsrite** [comment]
那是mp搜索过滤 逻辑问题 与插件无关，插件能给你订阅添加上清晰度设置就没问题

**Comment by dlovew** [comment]
> 那是mp搜索过滤 逻辑问题 与插件无关，插件能给你订阅添加上清晰度设置就没问题

栓q大佬，我后来在规则设置了清晰度就ok了，忘记关issue了
