### ISSUE TITLE
V2版无法使用Homepage

### ISSUE THREAD

**Issue by whsiny** [thsrite/MoviePilot-Plugins#107]
打开http://192.168.1.100:3003/api/v1/plugin/HomePage/statistic?apikey=JWG-yo6QgyY_Jam8NxQUTc0BrrN3YG5f
显示"detail": "API_KEY 校验不通过"

**Comment by thsrite** [comment]
apikey太复杂了吧，应该是主框架没传过来正确的key，建议把_ - 去掉
