### ISSUE TITLE
关于目录监控，希望能解决一下这个问题，目前是mp-v2

### ISSUE THREAD

**Issue by Whys8182** [thsrite/MoviePilot-Plugins#115]
有许多剧集，在tmdb里面有特殊的定位，例如《家有儿女》定位为儿童，《辛普森一家》定位为欧美剧。

我尝试在目录监控中，将它们分别按照我的要求，《家有儿女》硬链接到国产剧目录下，但有意思的是，国产剧目录下又生成了一个儿童目录，这个目录下硬链接出了《家有儿女》；
《辛普森一家》本意想硬链接到儿童目录下，虽然它确实在这个目录下，但与《家有儿女》相同，它也生成了一个在儿童目录下的分类文件夹“欧美剧”，并且在这个目录下硬链接出了《辛普森一家》。

原本希望的目录列表为/media/video/儿童/辛普森一家；/media/video/国产剧/家有儿女；

现在却变成了这样的目录/media/video/儿童/欧美剧/辛普森一家；/media/video/国产剧/儿童/家有儿女；

**Comment by thsrite** [comment]
目录监控插件走的是主程序的目录监控逻辑。 
主程序没问题理论上这个也没问题 
主程序有问题，插件也解决不了
---- 回复的原邮件 ----
***@***.***>发送日期2024年11月10日 12:05 ***@***.***> ***@***.***>主题[thsrite/MoviePilot-Plugins] 关于目录监控，希望能解决一下这个问题 (Issue #115)
有许多剧集，在tmdb里面有特殊的定位，例如《家有儿女》定位为儿童，《辛普森一家》定位为欧美剧。
我尝试在目录监控中，将它们分别按照我的要求，《家有儿女》硬链接到国产剧目录下，但有意思的是，国产剧目录下又生成了一个儿童目录，这个目录下硬链接出了《家有儿女》；
《辛普森一家》本意想硬链接到儿童目录下，虽然它确实在这个目录下，但与《家有儿女》相同，它也生成了一个在儿童目录下的分类文件夹“欧美剧”，并且在这个目录下硬链接出了《辛普森一家》。
原本希望的目录列表为/media/video/儿童/辛普森一家；/media/video/国产剧/家有儿女；
现在却变成了这样的目录/media/video/儿童/欧美剧/辛普森一家；/media/video/国产剧/儿童/家有儿女；

**Comment by Whys8182** [comment]
我目前主程序目录设置是从左到右，设置了电影、儿童、日番、国漫、电视剧，按照mp-v1识别上辛普森应该是落在儿童里，但是在mp-v2它却在儿童下面又生成了一个欧美剧，我觉得应该是插件的适配问题，是否能帮忙再检查一下呢。
/media/video/儿童/欧美剧/辛普森一家

**Comment by thsrite** [comment]
我说了 插件直接调用的主程序的整理功能，你直接用主程序目录监控试试呢？
