### ISSUE TITLE
STRM增量版更新1.1.2后会卡住不动

### ISSUE THREAD

**Issue by kettly1260** [thsrite/MoviePilot-Plugins#117]
【INFO】2024-11-10 20:04:11,917 - cloudstrmincrement - 扫描到增量文件 /home/mount/alist/aliyun/Movies/Detective.Conan.The.Bride.of.Halloween.2022.1080p.BluRay.DD5.1.x265-10bit-BATHD.mkv，正在开始处理
【INFO】2024-11-10 20:04:11,916 - cloudstrmincrement - 正在扫描增量目录 /home/mount/alist/aliyun/Movies
【INFO】2024-11-10 20:04:11,915 - cloudstrmincrement - 云盘strm生成任务开始
【INFO】2024-11-10 20:04:08,914 - cloudstrmincrement - 云盘增量监控执行服务启动，立即运行一次
【INFO】2024-11-10 19:55:28,421 - cloudstrmincrement - 扫描到增量文件 /home/mount/alist/aliyun/Movies/Detective.Conan.The.Bride.of.Halloween.2022.1080p.BluRay.DD5.1.x265-10bit-BATHD.mkv，正在开始处理
【INFO】2024-11-10 19:55:27,672 - cloudstrmincrement - 正在扫描增量目录 /home/mount/alist/aliyun/Movies
【INFO】2024-11-10 19:55:27,671 - cloudstrmincrement - 云盘strm生成任务开始
【INFO】2024-11-10 19:55:24,670 - cloudstrmincrement - 云盘增量监控执行服务启动，立即运行一次
【INFO】2024-11-10 17:46:27,535 - cloudstrmincrement - 扫描到增量文件 /home/mount/alist/aliyun/Movies/Detective.Conan.The.Bride.of.Halloween.2022.1080p.BluRay.DD5.1.x265-10bit-BATHD.mkv，正在开始处理
【INFO】2024-11-10 17:46:27,511 - cloudstrmincrement - 正在扫描增量目录 /home/mount/alist/aliyun/Movies
【INFO】2024-11-10 17:46:27,510 - cloudstrmincrement - 云盘strm生成任务开始
【INFO】2024-11-10 17:46:24,508 - cloudstrmincrement - 云盘增量监控执行服务启动，立即运行一次
【INFO】2024-11-10 02:22:53,207 - cloudstrmincrement - 云盘strm生成任务完成
【INFO】2024-11-10 02:22:53,206 - cloudstrmincrement - 云盘strm生成任务完成

**Comment by thsrite** [comment]
用 云盘strm助手 插件试试
