### ISSUE TITLE
 云盘同步删除v1.5.5版本 emby strm库无法同步删除云盘文件

### ISSUE THREAD

**Issue by tsreal** [thsrite/MoviePilot-Plugins#120]
> 首先感谢下大佬开发的诸多好用插件。之前v1的时候用的是**云盘文件删除 v1.3**插件，使用一切正常，升级到v2后插件库只有这个**云盘同步删除**插件。

### **查看日志发现似乎云盘文件路径未能正确替换：**
![image](https://github.com/user-attachments/assets/632e21e4-3c7b-4897-b528-bd08b889258d)

### **以下是测试流程：**

- ### **想要删除的emby库文件位置为 /mnt/ssd/115strm/测试/变形金刚.strm：**

![image](https://github.com/user-attachments/assets/81edc094-3642-483b-8897-c1f174f38d85)

- ### **在MPv2中对应位置为（我理解的是MoviePilot软连接路径）/ssd/115strm/测试/变形金刚.strm：**

![image](https://github.com/user-attachments/assets/9ea825e4-961b-4657-966e-d741ae54b930)

- ###  **网盘在MPv2中对应位置 /mnt/115/测试/变形金刚.strm：**

![image](https://github.com/user-attachments/assets/60473e73-c4c6-4285-b388-605282f0f288)

- ### **故插件配置为 /mnt/ssd/115strm:/ssd/115strm#/mnt/115：**

![image](https://github.com/user-attachments/assets/001b70cb-ea35-4cc7-9fa4-0f1a23378047)

**Comment by thsrite** [comment]
你配置的对  更新1.5.6试试
