### ISSUE TITLE
云盘Strm助手报错405

### ISSUE THREAD

**Issue by Juhuaaaa** [thsrite/MoviePilot-Plugins#122]
cookie为手机抓包的cookie，已尝试更换cookie无法解决，我朋友也是报错405，若目录配置错误望指出

日志：
![image](https://github.com/user-attachments/assets/dd86d93a-9824-4a85-94a1-7195d170690d)
设置：
![image](https://github.com/user-attachments/assets/f72efef7-8431-4235-b807-1d872ebf7e1e)
cd2挂载路径
![image](https://github.com/user-attachments/assets/cf961b79-bab2-4119-847d-4959819fc23c)
strm生成路径
![image](https://github.com/user-attachments/assets/ac971bc9-f678-4daa-ab64-5cbc043275cc)
cd2内115路径
![image](https://github.com/user-attachments/assets/e2ebc0e7-e770-4727-954c-b150ab43f135)

**Comment by thsrite** [comment]
405 风控了

**Comment by Juhuaaaa** [comment]
更换小程序cookie已解决问题
