### ISSUE TITLE
云盘Strm生成，扫cd2挂载云盘设置监控目录间隔的时间，监控太快115盘直接429

### ISSUE THREAD

**Issue by zengjiu** [thsrite/MoviePilot-Plugins#125]
云盘Strm生成，扫cd2挂载云盘设置监控目录间隔的时间，监控太快115盘直接429
Status(StatusCode="Internal", Detail="http error HttpError: status: 429 Too Many Requests, message: too many requests")

**Comment by thsrite** [comment]
那就用云盘strm助手 v2
