### ISSUE TITLE
下载器文件同步插件在MoviePilotV2版本中无法读取qBittorrent中的种子文件

### ISSUE THREAD

**Issue by MOMOTSI** [thsrite/MoviePilot-Plugins#127]
首先非常非常感谢大佬做的众多优秀插件

MoviePilot 版本：v2.0.2-v2.0.3
下载器文件同步版本：1.1.3
QB版本：qBittorrent v4.6.7（群晖套件安装）
TR版本：3.0.0（群晖套件安装）
问题描述：下载器文件同步插件在MoviePilotV2版本中无法读取QB中的种子文件，TR正常（V1版本QB、TR全部正常）。

插件日志（会一直卡在这里）：
【INFO】2024-11-13 14:38:42,417 - syncdownloadfiles - 下载器 qBittorrent 已完成种子数：924
【INFO】2024-11-13 14:38:42,172 - syncdownloadfiles - 开始扫描下载器 qBittorrent ...
【INFO】2024-11-13 14:38:42,170 - syncdownloadfiles - 开始同步下载器任务文件记录

MoviePilot 日志：
<html>
<body>

2024/11/13 15:00:43 | stdout | AttributeError: 'TorrentDictionary' instance has no attribute 'added_date'
-- | -- | --
2024/11/13 15:00:43 | stdout | raise AttributeError(
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/qbittorrentapi/_attrdict.py", line 141, in __getattr__
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | torrents = sorted(torrents, key=lambda x: x.added_date, reverse=True)
2024/11/13 15:00:43 | stdout | File "/app/app/plugins/syncdownloadfiles/__init__.py", line 243, in <lambda>
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | torrents = sorted(torrents, key=lambda x: x.added_date, reverse=True)
2024/11/13 15:00:43 | stdout | File "/app/app/plugins/syncdownloadfiles/__init__.py", line 243, in __get_origin_torrents
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | torrents = self.__get_origin_torrents(torrents, downloader)
2024/11/13 15:00:43 | stdout | File "/app/app/plugins/syncdownloadfiles/__init__.py", line 116, in sync
2024/11/13 15:00:43 | stdout | self.sync()
2024/11/13 15:00:43 | stdout | File "/app/app/plugins/syncdownloadfiles/__init__.py", line 87, in init_plugin
2024/11/13 15:00:43 | stdout | plugin.init_plugin(conf)
2024/11/13 15:00:43 | stdout | File "/app/app/core/plugin.py", line 188, in init_plugin
2024/11/13 15:00:43 | stdout | PluginManager().init_plugin(plugin_id, conf)
2024/11/13 15:00:43 | stdout | File "/app/app/api/endpoints/plugin.py", line 307, in set_plugin_config
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | result = context.run(func, *args)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 943, in run
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | return await future
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | return await get_async_backend().run_sync_in_worker_thread(
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | return await anyio.to_thread.run_sync(func, *args)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | return await run_in_threadpool(dependant.call, **values)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 165, in run_endpoint_function
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | raw_response = await run_endpoint_function(
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | response = await func(request)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
2024/11/13 15:00:43 | stdout | await self.app(scope, receive, send)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
2024/11/13 15:00:43 | stdout | await route.handle(scope, receive, send)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
2024/11/13 15:00:43 | stdout | await self.app(scope, receive, send)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2024/11/13 15:00:43 | stdout | raise e
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2024/11/13 15:00:43 | stdout | await self.app(scope, receive, sender)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
2024/11/13 15:00:43 | stdout | raise exc
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
2024/11/13 15:00:43 | stdout | await self.app(scope, receive, send)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
2024/11/13 15:00:43 | stdout | await self.simple_response(scope, receive, send, request_headers=headers)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
2024/11/13 15:00:43 | stdout | await self.app(scope, receive, _send)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
2024/11/13 15:00:43 | stdout | raise exc
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
2024/11/13 15:00:43 | stdout | await self.middleware_stack(scope, receive, send)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
2024/11/13 15:00:43 | stdout | await super().__call__(scope, receive, send)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 276, in __call__
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | return await self.app(scope, receive, send)
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2024/11/13 15:00:43 | stdout | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/11/13 15:00:43 | stdout | result = await app(  # type: ignore[func-returns-value]
2024/11/13 15:00:43 | stdout | File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
2024/11/13 15:00:43 | stdout | Traceback (most recent call last):
2024/11/13 15:00:43 | stdout | [31mERROR[0m:    Exception in ASGI application
2024/11/13 15:00:43 | stdout | [32mINFO[0m:     172.17.0.1:0 - "[1mPUT /api/v1/plugin/SyncDownloadFiles HTTP/1.1[0m" [91m500 Internal Server Error[0m
2024/11/13 15:00:43 | stdout | [32mINFO:[0m    syncdownloadfiles - 下载器 qBittorrent 已完成种子数：924
2024/11/13 15:00:43 | stdout | [32mINFO:[0m    syncdownloadfiles - 开始扫描下载器 qBittorrent ...
2024/11/13 15:00:43 | stdout | [32mINFO:[0m    syncdownloadfiles - 开始同步下载器任务文件记录
2024/11/13 15:00:41 | stdout | [32mINFO[0m:     172.17.0.1:0 - "[1mGET /api/v1/plugin/SyncDownloadFiles HTTP/1.1[0m" [32m200 OK[0m
2024/11/13 15:00:41 | stdout | [32mINFO[0m:     172.17.0.1:0 - "[1mGET /api/v1/plugin/form/SyncDownloadFiles HTTP/1.1[0m" [32m200 OK[0m

</body>
</html>

**Comment by thsrite** [comment]
更新1.1.4
