### ISSUE TITLE
媒体文件同步删除 源文件及种子 无法删除

### ISSUE THREAD

**Issue by paysenyu** [thsrite/MoviePilot-Plugins#129]
【INFO】2024-11-14 11:20:08,925 - mediasyncdel - 同步删除 电影 临时劫案 991197 完成！
【INFO】2024-11-14 11:20:08,924 - mediasyncdel - 查询到 136bd8171bd34e8aa906f4806ee5eaa54091151f 辅种历史 []
【INFO】2024-11-14 11:20:08,922 - mediasyncdel - 删除源下载器下载任务：qb - 136bd8171bd34e8aa906f4806ee5eaa54091151f
【INFO】2024-11-14 11:20:08,921 - mediasyncdel - 查询种子任务 136bd8171bd34e8aa906f4806ee5eaa54091151f 文件已全部删除，执行删除种子操作
【INFO】2024-11-14 11:20:08,920 - mediasyncdel - 查询到 qb-136bd8171bd34e8aa906f4806ee5eaa54091151f 转种历史 None
【INFO】2024-11-14 11:20:08,908 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-11-14 11:20:08,907 - mediasyncdel - 正在同步删除电影 临时劫案 991197

日志里面文件和种子都删除了。实际源文件和种子都还在。

权限也检查过了是 nobody rw rw rw . 

用的是mpv2

**Comment by thsrite** [comment]
群里问问吧，这个表没问题

**Comment by paysenyu** [comment]
> 群里问问吧，这个插件没问题

我这确实也尝试了好多方法都不行

插件更新到最新的 1.8.4了

然后是用mp2 手动通过 文件管理搜刮文件来测试 （这样做的预期是删除源文件） 
种子记录肯定是没有的，但实际情况是日志里面还会记录已删除对应的种子文件

应该是和下载记录同步插件有关

不知道是否一定需要重新下载的资源才可以？

**Comment by thsrite** [comment]
前提是经过mp下载 整理 转种 辅种等一系列流程才可以同步删除
你如果之前v1下载整理的种子，到v2又没迁移相应数据库记录的话，肯定无效

**Comment by paysenyu** [comment]
> 前提是经过mp下载 整理 转种 辅种等一系列流程才可以同步删除 你如果之前v1下载整理的种子，到v2又没迁移相应数据库记录的话，肯定无效

感谢抽空回复，

从v1迁移到v2后，我用了历史记录迁移插件，历史记录看了下也是一一对应的，同时文件路径等都是一一匹配未改变的。

然后我做了如下操作：从mpv2的文件管理中 ， 手动定位到曾经下载过的文件，然后点击整理
此时在历史记录中生成了对应的搜刮记录， 有源文件路径及媒体库路径
接下来在 emby 操作删除
插件日志记录如下 ：

【DEBUG】2024-11-15 11:16:54,756 - tmdbapi.py - 1019828 查询结果：默杀：无声之地
【DEBUG】2024-11-15 11:16:54,755 - tmdbapi.py - 正在查询TMDB电影：1019828 ...
【DEBUG】2024-11-15 11:16:54,753 - chain - 请求模块执行：obtain_specific_image ...
【DEBUG】2024-11-15 11:16:54,505 - tmdbapi.py - 1019828 查询结果：默杀：无声之地
【DEBUG】2024-11-15 11:16:54,505 - tmdbapi.py - 正在查询TMDB电影：1019828 ...
【DEBUG】2024-11-15 11:16:54,504 - chain - 请求模块执行：obtain_specific_image ...
【INFO】2024-11-15 11:16:54,503 - mediasyncdel - 同步删除 电影 默杀：无声之地 1019828 完成！
【INFO】2024-11-15 11:16:54,503 - mediasyncdel - 查询到 0b51adf935edfaef144cb1524943739746ffafe7 辅种历史 []
【DEBUG】2024-11-15 11:16:54,501 - chain - 请求模块执行：remove_torrents ...
【INFO】2024-11-15 11:16:54,500 - mediasyncdel - 删除源下载器下载任务：qb - 0b51adf935edfaef144cb1524943739746ffafe7
【INFO】2024-11-15 11:16:54,500 - mediasyncdel - 查询种子任务 0b51adf935edfaef144cb1524943739746ffafe7 文件已全部删除，执行删除种子操作
【INFO】2024-11-15 11:16:54,498 - mediasyncdel - 查询到 qb-0b51adf935edfaef144cb1524943739746ffafe7 转种历史 None
【DEBUG】2024-11-15 11:16:54,497 - chain - 请求模块执行：delete_file ...
【INFO】2024-11-15 11:16:54,476 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-11-15 11:16:54,475 - mediasyncdel - 正在同步删除电影 默杀：无声之地 1019828

按日志来看，种子记录是有的，源文件应该也提示删除了。  

实际去看只是删除了mpv2的历史记录和媒体库文件。

源文件和种子依旧在， 并且我去unraid检查了源文件的权限，是nobody rw rw rw ， 也给mpv2 赋予了读写权限的。

所以目前我自己排查确实陷入了困境，无法进一步了。

**Comment by paysenyu** [comment]
更新一下

刚才用mpv2 全新下载的一个种子，然后可以正常联动删除。

就是历史记录里面的，依旧是源文件都不会被删掉，希望有办法可以排查一下这方面。 日志开了debug 暂时未发现有报错之类的

历史记录也都是从v1 用插件迁移到 v2的。

**Comment by thsrite** [comment]
不单单有历史记录啊  还有插件的一些数据

v2上全新下载删除没问题就是没问题

至于历史记录里删除删不掉源文件，你去主程序那里提issue

**Comment by paysenyu** [comment]
> 不单单有历史记录啊 还有插件的一些数据
> 
> v2上全新下载删除没问题就是没问题
> 
> 至于历史记录里删除删不掉源文件，你去主程序那里提issue

好的，感谢T佬。。。 我再继续尝试。
