### ISSUE TITLE
EMBY观影报告插件中的添加映射目录问题

### ISSUE THREAD

**Issue by saarjoye** [thsrite/MoviePilot-Plugins#13]
将本项目/data/EmbyReporter/rss/下文件路径映射到mp容器内

我在我的EMBY库目录中没有找到这个embyreporter的文件，是否自主创建该目录呀

**Comment by saarjoye** [comment]
Job "Emby观影报告 (trigger: date[2024-01-17 13:35:38 CST], next run at: 2024-01-17 13:35:38 CST)" raised an exception

手动创建文件夹运行后，一直提示这个错误

**Comment by LAN-Cliv** [comment]
> 作业“Emby观影报告（触发器：date[2024-01-17 13：35：38 CST]，下次运行时间：2024-01-17 13：35：38 CST）”引发异常
> 
> 手动创建文件夹运行后，一直提示这个错误

这是让你从作者的GITHUB的项目代码里下载这几个文件，然后把这几个文件映射到MP容器内

**Comment by saarjoye** [comment]
我下载素材文件以后。映射完成运行插件提示生成海报失败

**Comment by LAN-Cliv** [comment]
> 我下载素材文件以后。映射完成运行插件提示生成海报失败

是有这个问题，但看日志太简单，不知道为啥，我在emby的相关插件中设置了过滤时长，然后又调回，然后又正常了。

**Comment by autunn** [comment]
全部都设置好了，也能推送消息到微信了，但是图片是白板，什么信息都没有，数值都设置到100了，还要更大？

**Comment by LAN-Cliv** [comment]
> 全部都设置好了，也能推送消息到微信了，但是图片是白板，什么信息都没有，数值都设置到100了，还要更大？

貌似被微信限制了，PC微信能看到缩略图，手机是白板，但TG是正常的

**Comment by autunn** [comment]
> > 全部都设置好了，也能推送消息到微信了，但是图片是白板，什么信息都没有，数值都设置到100了，还要更大？
> 
> 貌似被微信限制了，PC微信能看到缩略图，手机是白板，但TG是正常的

pc微信看也是白板，没有缩略图

**Comment by autunn** [comment]
作者貌似不使用企业微信来配合这个插件，头疼

**Comment by LevineWoo** [comment]
我转到tg的是空的
![](https://i.imgur.com/jcr9m4r.png)
![](https://i.imgur.com/cKXfdli.png)
是否有哪里没弄对呢？
