### ISSUE TITLE
V2的云盘Strm助手只能实现115同步strm到本地吗

### ISSUE THREAD

**Issue by AceCandy** [thsrite/MoviePilot-Plugins#130]
想问下  V2的云盘Strm助手插件的功能是只能实现115同步strm到本地吗
我希望将本地的文件上传到115并在本地生成strm  能用这个插件么

**Comment by thsrite** [comment]
是，能

**Comment by AceCandy** [comment]
> 是，能

想问下佬具体怎么写呢  我是比如mp下载在/mnt/download这个目录   硬链到/mnt/media目录整理  然后这个目录下就有元数据和视频文件了   我想监控/mnt/media这个目录将其中的视频目录上传到cd2挂载的/cloud/media目录下然后生成对应的strm到之前视频文件的位置
