### ISSUE TITLE
云盘strm助手同步strm生成路径

### ISSUE THREAD

**Issue by mting1117** [thsrite/MoviePilot-Plugins#131]
经测试，云盘路径仅能识别一级目录
/mnt/CloudNAS/CloudDrive#/mnt/tools/moviepilot-v2/strm#/我的接收#{local_file}
此目录规则下，媒体文件夹内的strm可以在/mnt/tools/moviepilot-v2/strm内新建对应文件夹并生成strm

/mnt/CloudNAS/CloudDrive#/mnt/tools/moviepilot-v2/strm#/媒体/电影#{local_file}
此目录规则下媒体文件夹内的strm会在mp内根目录下新建对应文件夹并生成strm，无法生成在目录规则内指定的文件夹，且strm内路径也是云盘内路径，非云盘挂载到本地的路径

麻烦大佬有时间的话可以测试下
![Snipaste_2024-11-14_20-32-12](https://github.com/user-attachments/assets/9ced5f5a-7084-4d42-a51b-047d0fd924c2)
![Snipaste_2024-11-14_20-32-55](https://github.com/user-attachments/assets/b6385f07-1e57-4477-8285-a32558c5b927)

**Comment by thsrite** [comment]
v1.0.9
