### ISSUE TITLE
尊敬的作者大大你好有个问题向您反馈    插件  目录实时监控 v2.5.3

### ISSUE THREAD

**Issue by wanpijun2** [thsrite/MoviePilot-Plugins#133]
网盘 自动整理的时候  V2版的插件不能像V1一样自动整理到mp的媒体库目录么        我是 设置了目标路径可以整理成功了     还有作者大大  V2 的插件我上传替换资源的 他的默认覆盖模式是从不   也是吃不到媒体库的设置原因么     可以稍稍改一下么
![1b7d753a-5f74-4d35-90b9-3ca31ee62b3d](https://github.com/user-attachments/assets/568150a2-a584-4709-adba-d1302493fdc8)
![image](https://github.com/user-attachments/assets/2f3882ef-e899-44a0-9355-096fac93b4f2)

**Comment by wanpijun2** [comment]
我是本地 和网盘 一起使用的 作者大大 辛苦了

**Comment by thsrite** [comment]
更新2.5.4

**Comment by wanpijun2** [comment]
> 更新2.5.4

作者 大大 感谢 辛苦了   暂时还没收到推送更新  爱你
