### ISSUE TITLE
关于目录实时监控在监控网盘时被流控的问题

### ISSUE THREAD

**Issue by mting1117** [thsrite/MoviePilot-Plugins#134]
大佬，目录实时监控，监控网盘通过cd2挂载到本地的目录时，大概一天左右后实时触发会失效，只能通过电报机器人的指令来手动启动插件来整理，我看了mp的wiki，说是因为请求过多被流控，目前测试重启mp后即可重新生效，有没有办法在仅重启插件的情况下，使其重新生效，并融合在电报机器人的菜单里

**Comment by thsrite** [comment]
安装 插件重装重载 插件
