### ISSUE TITLE
咨询云盘Strm助手 - 配置格式

### ISSUE THREAD

**Issue by qqcomeup** [thsrite/MoviePilot-Plugins#135]
你好T佬，咨询下生成strm配置格式
MoviePilot中云盘挂载本地的路径=cd2挂载本地=/cd2/CloudDrive/115k/test
MoviePilot中strm生成路径=/cd2/test
云盘路径=http://192.168.8.4:5244/d/115k/test
是否搭配/cd2/CloudDrive/115k/test#/cd2/test#http://192.168.8.4:5244/d/115k/test#{cloud_file}这样呢？
还是/cd2/CloudDrive/115k/test#/cd2/test#http://192.168.8.4:5244/d/115k/test{cloud_file}
一直运行不成功，请指导谢谢

日志如下
【INFO】2024-11-16 21:00:37,506 - cloudstrmcompanion - 云盘Strm助手同步生成任务完成
【ERROR】2024-11-16 21:00:37,485 - cloudstrmcompanion - http://192.168.8.4:5244/d/115k/test 目录不存在或路径错误
【INFO】2024-11-16 21:00:37,285 - cloudstrmcompanion - 开始生成 http://192.168.8.4:5244/d/115k/test 目录树
【INFO】2024-11-16 21:00:37,258 - cloudstrmcompanion - 云盘Strm助手同步生成任务开始
【INFO】2024-11-16 21:00:34,232 - cloudstrmcompanion - 云盘Strm助手全量执行服务启动，立即运行一次
【INFO】2024-11-16 21:00:34,199 - cloudstrmcompanion - /cd2/CloudDrive/115k/test 的Strm生成实时监控服务启动
【INFO】2024-11-16 21:00:34,153 - cloudstrmcompanion - 旧数据索引清理完成

**Comment by thsrite** [comment]
/cd2/test写网盘上根路径

**Comment by qqcomeup** [comment]
大师我又悟了。T佬可否改进下URL解码合并一起？
/cd2/CloudDrive/115k/test#/cd2/test#/test#http://192.168.8.4:5244/d/115k{cloud_file}
本地挂载路径#生成strm本地路径#网盘路径#格式化指下面strm格式化方式
strm格式化地址会+网盘路径合并=地址+URI编码一起的
比如这个地址=http://192.168.8.4:5244/d/115k%2Ftest%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%20-%202160p%20%7B%5Btmdbid%3D1197437%5D%7D.mkv
解码=http://192.168.8.4:5244/d/115k/test/爆款好人 (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.mkv
这样能直观判定内容是否正确。
strm格式化方式，自行把()替换为alist/cd2上路径，url编码格式：1.本地源文件路径：{local_file}。2.alist路径：http://192.168.31.103:5244/d(){cloud_file}。3.cd2路径：http://192.168.31.103:19798/static/http/192.168.31.103:19798/False/(){cloud_file}。4.其他api路径：http://192.168.31.103:2001/{cloud_file}

**Comment by thsrite** [comment]
> 大师我又悟了。T佬可否改进下URL解码合并一起？ /cd2/CloudDrive/115k/test#/cd2/test#/test#[http://192.168.8.4:5244/d/115k{cloud_file}](http://192.168.8.4:5244/d/115k%7Bcloud_file%7D) 本地挂载路径#生成strm本地路径#网盘路径#格式化指下面strm格式化方式 strm格式化地址会+网盘路径合并=地址+URI编码一起的 比如这个地址=http://192.168.8.4:5244/d/115k%2Ftest%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%20-%202160p%20%7B%5Btmdbid%3D1197437%5D%7D.mkv 解码=[http://192.168.8.4:5244/d/115k/test/爆款好人](http://192.168.8.4:5244/d/115k/test/%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA) (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.mkv 这样能直观判定内容是否正确，也不影响播放。 strm格式化方式，自行把()替换为alist/cd2上路径，url编码格式：1.本地源文件路径：{local_file}。2.alist路径：[http://192.168.31.103:5244/d(){cloud_file}。3.cd2路径：http://192.168.31.103:19798/static/http/192.168.31.103:19798/False/(){cloud_file}。4.其他api路径：http://192.168.31.103:2001/{cloud_file}](http://192.168.31.103:5244/d()%7Bcloud_file%7D%E3%80%823.cd2%E8%B7%AF%E5%BE%84%EF%BC%9Ahttp://192.168.31.103:19798/static/http/192.168.31.103:19798/False/()%7Bcloud_file%7D%E3%80%824.%E5%85%B6%E4%BB%96api%E8%B7%AF%E5%BE%84%EF%BC%9Ahttp://192.168.31.103:2001/%7Bcloud_file%7D)

1.1.6改了，不过要http://192.168.8.4:5244/d(/115k){cloud_file}这样填写，因为我要知道/115k这部分是要url编码的

**Comment by qqcomeup** [comment]
> 1.1.6改了，不过要[http://192.168.8.4:5244/d(/115k){cloud_file}这样填写，因为我要知道/115k这部分是要url编码的](http://192.168.8.4:5244/d(/115k)%7Bcloud_file%7D%E8%BF%99%E6%A0%B7%E5%A1%AB%E5%86%99%EF%BC%8C%E5%9B%A0%E4%B8%BA%E6%88%91%E8%A6%81%E7%9F%A5%E9%81%93/115k%E8%BF%99%E9%83%A8%E5%88%86%E6%98%AF%E8%A6%81url%E7%BC%96%E7%A0%81%E7%9A%84)

-------------------
你好T佬，刚试通知没问题完美修复！！
不过按照佬所格式写没实现。
/cd2/CloudDrive/115k/test#/cd2/test#/test#http://192.168.8.4:5244/d(/115k){cloud_file}创建实现不了直观化路径
![QQ图片20241118110615](https://github.com/user-attachments/assets/8faa1c55-fcf3-4bdd-b948-9fc031387901)

创建http://192.168.8.4:5244/d/115k/test/叛军岭 (2024)/叛军岭 (2024) - 1080p {[tmdbid=646097]}.mkv格式
也可以emby直接观看/xx2也不影响。


日志如下：
 cloudstrmcompanion - 云盘Strm助手同步生成任务开始
INFO:    cloudstrmcompanion - 开始生成 /test 目录树
INFO:    cloudstrmcompanion - 等待目录树生成完成，剩余重试 59 次
INFO:    cloudstrmcompanion - /test 目录树下载成功
INFO:    cloudstrmcompanion - 扫描到新文件 /test/龙的传人 (1991)/龙的传人 (1991) - 1080p {[tmdbid=56118]}.mkv，正在开始处理
INFO:    cloudstrmcompanion - 创建目标文件夹 /cd2/test/龙的传人 (1991)
INFO:    cloudstrmcompanion - 创建strm文件成功 /cd2/test/龙的传人 (1991)/龙的传人 (1991) - 1080p {[tmdbid=56118]}.strm -> http://192.168.8.4:5244/d/115k%2Ftest%2F%E9%BE%99%E7%9A%84%E4%BC%A0%E4%BA%BA%20%281991%29%2F%E9%BE%99%E7%9A%84%E4%BC%A0%E4%BA%BA%20%281991%29%20-%201080p%20%7B%5Btmdbid%3D56118%5D%7D.mkv
INFO:    cloudstrmcompanion - 扫描到新文件 /test/叛军岭 (2024)/叛军岭 (2024) - 1080p {[tmdbid=646097]}.mkv，正在开始处理
INFO:    cloudstrmcompanion - 创建目标文件夹 /cd2/test/叛军岭 (2024)
INFO:    cloudstrmcompanion - 创建strm文件成功 /cd2/test/叛军岭 (2024)/叛军岭 (2024) - 1080p {[tmdbid=646097]}.strm -> http://192.168.8.4:5244/d/115k%2Ftest%2F%E5%8F%9B%E5%86%9B%E5%B2%AD%20%282024%29%2F%E5%8F%9B%E5%86%9B%E5%B2%AD%20%282024%29%20-%201080p%20%7B%5Btmdbid%3D646097%5D%7D.mkv
INFO:    cloudstrmcompanion - 扫描到新文件 /test/爆款好人 (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.mkv，正在开始处理
INFO:    cloudstrmcompanion - 创建目标文件夹 /cd2/test/爆款好人 (2024)
INFO:    cloudstrmcompanion - 创建strm文件成功 /cd2/test/爆款好人 (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.strm -> http://192.168.8.4:5244/d/115k%2Ftest%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%20-%202160p%20%7B%5Btmdbid%3D1197437%5D%7D.mkv
INFO:    cloudstrmcompanion - 开始写入本地文件 /config/plugins/CloudStrmCompanion/cloud_files.json
INFO:    cloudstrmcompanion - 云盘Strm助手同步生成任务完成

**Comment by thsrite** [comment]
> http://192.168.8.4:5244/d(/115k){cloud_file}
创建[http://192.168.8.4:5244/d/115k/test/叛军岭](http://192.168.8.4:5244/d/115k/test/%E5%8F%9B%E5%86%9B%E5%B2%AD) (2024)/叛军岭 (2024) - 1080p {[tmdbid=646097]}.mkv格式
也可以emby直接观看/xx2也不影响。


emby、infuse、获取其他三方客户端，以及直连都没影响吗？

**Comment by qqcomeup** [comment]
> > [http://192.168.8.4:5244/d(/115k){cloud_file}](http://192.168.8.4:5244/d(/115k)%7Bcloud_file%7D)
> > 创建[http://192.168.8.4:5244/d/115k/test/叛军岭](http://192.168.8.4:5244/d/115k/test/%E5%8F%9B%E5%86%9B%E5%B2%AD) (2024)/叛军岭 (2024) - 1080p {[tmdbid=646097]}.mkv格式
> > 也可以emby直接观看/xx2也不影响。
> 
> emby、infuse、获取其他三方客户端，以及直连都没影响吗？

----------------------
yamby emby senplayer infuse 实测emby内网,外域名embyxx2,都没问题.丢地址浏览器也能直接下载。

**Comment by thsrite** [comment]
> http://192.168.8.4:5244/d(/115k){cloud_file}
1.1.7那还是下面形式
http://192.168.8.4:5244/d/115k{cloud_file}
谢谢告知

**Comment by thsrite** [comment]
Strm重定向 可以解码重新写入strm  强迫症可以改下

**Comment by qqcomeup** [comment]
收到升级立马实测。
strm地址为：http://192.168.8.4:5244/d/115k/test/爆款好人 (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.mkv
实测yamby emby senplayer infuse ，完美播放没问题。
![QQ图片20241118122631](https://github.com/user-attachments/assets/510ccdd9-2174-46fb-ac55-0fb3ec1f3e35)

**Comment by thsrite** [comment]
> 收到升级立马实测。 strm地址为：[http://192.168.8.4:5244/d/115k/test/爆款好人](http://192.168.8.4:5244/d/115k/test/%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA) (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.mkv 实测yamby emby senplayer infuse ，完美播放没问题。 ![QQ图片20241118122631](https://private-user-images.githubusercontent.com/185712511/387063909-510ccdd9-2174-46fb-ac55-0fb3ec1f3e35.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE5MDQ5MTMsIm5iZiI6MTczMTkwNDYxMywicGF0aCI6Ii8xODU3MTI1MTEvMzg3MDYzOTA5LTUxMGNjZGQ5LTIxNzQtNDZmYi1hYzU1LTBmYjNlYzFmM2UzNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExOFQwNDM2NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NTAzNTViMDMxMmJlMDQ0Y2Y4ZjgxYTZmYWFmOTc0NmY3YWQ0OTJkMmM0ZmI1NzBmNzZlOTMxNmEyYTEzMWU2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zbJmHq6MtJ2sBCmfi-2S_ZLeIfJHdXKCsgths2Nw-Ss)
(๑•̀ㅂ•́)و✧
