### ISSUE TITLE
关于云盘strm助手生成strm后emby入库的请求

### ISSUE THREAD

**Issue by mting1117** [thsrite/MoviePilot-Plugins#136]
大佬，请教一个问题，emby媒体库的实时监控的逻辑，新增一集电视剧只会扫描这一集但新增一部电视剧或者电影会扫描整个媒体库，多少会有点影响入库的效率，是否有必要增加一个生成strm后主动通知emby去扫描该路径的strm文件达到准确入库的目的，从而提高效率。或者说有没有其他路子可以改善这一情况，之前在auto symlink的常用工具-emby通知是这样做的。
![SmartSelect_20241117_103748_YJBrowser](https://github.com/user-attachments/assets/36519574-0acf-42e4-8ea4-95ed5f0a1565)
![SmartSelect_20241117_103838_YJBrowser](https://github.com/user-attachments/assets/38d5a4e7-ff41-47bf-8167-82142f294a86)

**Comment by thsrite** [comment]
还用as呗

**Comment by mting1117** [comment]
> 还用as呗

想着能用一个工具解决一整套流程最好，工具多了，有些环节衔接容易出问题🥲

**Comment by thsrite** [comment]
v1.1.5

**Comment by mting1117** [comment]
> v1.1.5

感谢大佬的更新
