### ISSUE TITLE
strm助手会循环处理媒体信息，也没发送出去。

### ISSUE THREAD

**Issue by qqcomeup** [thsrite/MoviePilot-Plugins#137]
你好T佬，插件日志循环提醒发送，实际未发出去一直处理。
还有可否改下
大师我又悟了。T佬可否改进下URL解码合并一起？
strm格式化地址会+网盘路径合并=地址+URI编码一起的
比如这个地址=http://192.168.8.4:5244/d/115k%2Ftest%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%20-%202160p%20%7B%5Btmdbid%3D1197437%5D%7D.mkv
解码=[http://192.168.8.4:5244/d/115k/test/爆款好人](http://192.168.8.4:5244/d/115k/test/%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA) (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.mkv
这样能直观判定内容是否正确，也不影响播放。
监控模式好像也依赖cd2，但是cd2一刷新就是429错误，可否改成监控115曲奇网盘内的。
【INFO】2024-11-17 15:32:22,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:32:22,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:32:22,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:32:07,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:32:07,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:32:07,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:31:52,426 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:31:52,425 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:31:52,424 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:31:37,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:31:37,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:31:37,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:31:22,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:31:22,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:31:22,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:31:07,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:31:07,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:31:07,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:30:52,537 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:30:52,484 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:30:52,438 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:30:37,508 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:30:37,480 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:30:37,445 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:30:22,587 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:30:22,546 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:30:22,504 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:30:07,530 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:30:07,481 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:30:07,440 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:29:52,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:29:52,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:29:52,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:29:37,426 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:29:37,425 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:29:37,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:29:22,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:29:22,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:29:22,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:29:07,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:29:07,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:29:07,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:28:52,426 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:28:52,425 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:28:52,424 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:28:37,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:28:37,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:28:37,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:28:22,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:28:22,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:28:22,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:28:07,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:28:07,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:28:07,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:27:59,448 - cloudstrmcompanion - 云盘Strm助手同步生成任务完成/config/plugins/CloudStrmCompanion/cloud_files.json
【INFO】2024-11-17 15:27:59,426 - cloudstrmcompanion - 创建strm文件成功 /cd2/test/爆款好人 (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.strm -> http://192.168.8.4:5244/d/115k%2Ftest%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%20-%202160p%20%7B%5Btmdbid%3D1197437%5D%7D.mkv
【INFO】2024-11-17 15:27:59,424 - cloudstrmcompanion - 扫描到新文件 /test/爆款好人 (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.mkv，正在开始处理
【INFO】2024-11-17 15:27:59,403 - cloudstrmcompanion - 创建strm文件成功 /cd2/test/叛军岭 (2024)/叛军岭 (2024) - 1080p {[tmdbid=646097]}.strm -> http://192.168.8.4:5244/d/115k%2Ftest%2F%E5%8F%9B%E5%86%9B%E5%B2%AD%20%282024%29%2F%E5%8F%9B%E5%86%9B%E5%B2%AD%20%282024%29%20-%201080p%20%7B%5Btmdbid%3D646097%5D%7D.mkv
【INFO】2024-11-17 15:27:59,400 - cloudstrmcompanion - 扫描到新文件 /test/叛军岭 (2024)/叛军岭 (2024) - 1080p {[tmdbid=646097]}.mkv，正在开始处理
【INFO】2024-11-17 15:27:59,379 - cloudstrmcompanion - 创建strm文件成功 /cd2/test/龙的传人 (1991)/龙的传人 (1991) - 1080p {[tmdbid=56118]}.strm -> http://192.168.8.4:5244/d/115k%2Ftest%2F%E9%BE%99%E7%9A%84%E4%BC%A0%E4%BA%BA%20%281991%29%2F%E9%BE%99%E7%9A%84%E4%BC%A0%E4%BA%BA%20%281991%29%20-%201080p%20%7B%5Btmdbid%3D56118%5D%7D.mkv
【INFO】2024-11-17 15:27:59,376 - cloudstrmcompanion - 扫描到新文件 /test/龙的传人 (1991)/龙的传人 (1991) - 1080p {[tmdbid=56118]}.mkv，正在开始处理
【INFO】2024-11-17 15:27:59,247 - cloudstrmcompanion - /test 目录树下载成功
【INFO】2024-11-17 15:27:55,727 - cloudstrmcompanion - 等待目录树生成完成，剩余重试 59 次
【INFO】2024-11-17 15:27:55,429 - cloudstrmcompanion - 开始生成 /test 目录树
【INFO】2024-11-17 15:27:55,428 - cloudstrmcompanion - 云盘Strm助手同步生成任务开始
【INFO】2024-11-17 15:27:52,426 - cloudstrmcompanion - 云盘Strm助手全量执行服务启动，立即运行一次
【INFO】2024-11-17 15:27:52,425 - cloudstrmcompanion - /cd2/CloudDrive/115k/test 的Strm生成实时监控服务启动
【INFO】2024-11-17 15:27:52,415 - cloudstrmcompanion - 旧数据索引清理完成
【INFO】2024-11-17 15:27:52,413 - cloudstrmcompanion - 开始清理旧数据索引
【INFO】2024-11-17 15:27:28,200 - cloudstrmcompanion - /cd2/CloudDrive/115k/test 的Strm生成实时监控服务启动

**Comment by thsrite** [comment]
更新
---- 回复的原邮件 ----
***@***.***>发送日期2024年11月17日 15:31 ***@***.***> ***@***.***>主题[thsrite/MoviePilot-Plugins] strm助手会循环处理媒体信息，也没发送出去。 (Issue #137)
你好T佬。
【INFO】2024-11-17 15:29:22,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:29:22,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:29:22,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:29:07,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:29:07,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:29:07,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:28:52,426 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:28:52,425 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:28:52,424 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:28:37,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:28:37,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:28:37,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:28:22,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:28:22,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:28:22,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:28:07,425 - cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
【INFO】2024-11-17 15:28:07,424 - cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
【INFO】2024-11-17 15:28:07,423 - cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
【INFO】2024-11-17 15:27:59,448 - cloudstrmcompanion - 云盘Strm助手同步生成任务完成
【INFO】2024-11-17 15:27:59,447 - cloudstrmcompanion - 开始写入本地文件 /config/plugins/CloudStrmCompanion/cloud_files.json
【INFO】2024-11-17 15:27:59,426 - cloudstrmcompanion - 创建strm文件成功 /cd2/test/爆款好人 (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.strm -> http://192.168.8.4:5244/d/115k%2Ftest%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%2F%E7%88%86%E6%AC%BE%E5%A5%BD%E4%BA%BA%20%282024%29%20-%202160p%20%7B%5Btmdbid%3D1197437%5D%7D.mkv
【INFO】2024-11-17 15:27:59,424 - cloudstrmcompanion - 扫描到新文件 /test/爆款好人 (2024)/爆款好人 (2024) - 2160p {[tmdbid=1197437]}.mkv，正在开始处理
【INFO】2024-11-17 15:27:59,403 - cloudstrmcompanion - 创建strm文件成功 /cd2/test/叛军岭 (2024)/叛军岭 (2024) - 1080p {[tmdbid=646097]}.strm -> http://192.168.8.4:5244/d/115k%2Ftest%2F%E5%8F%9B%E5%86%9B%E5%B2%AD%20%282024%29%2F%E5%8F%9B%E5%86%9B%E5%B2%AD%20%282024%29%20-%201080p%20%7B%5Btmdbid%3D646097%5D%7D.mkv
【INFO】2024-11-17 15:27:59,400 - cloudstrmcompanion - 扫描到新文件 /test/叛军岭 (2024)/叛军岭 (2024) - 1080p {[tmdbid=646097]}.mkv，正在开始处理
【INFO】2024-11-17 15:27:59,379 - cloudstrmcompanion - 创建strm文件成功 /cd2/test/龙的传人 (1991)/龙的传人 (1991) - 1080p {[tmdbid=56118]}.strm -> http://192.168.8.4:5244/d/115k%2Ftest%2F%E9%BE%99%E7%9A%84%E4%BC%A0%E4%BA%BA%20%281991%29%2F%E9%BE%99%E7%9A%84%E4%BC%A0%E4%BA%BA%20%281991%29%20-%201080p%20%7B%5Btmdbid%3D56118%5D%7D.mkv
【INFO】2024-11-17 15:27:59,376 - cloudstrmcompanion - 扫描到新文件 /test/龙的传人 (1991)/龙的传人 (1991) - 1080p {[tmdbid=56118]}.mkv，正在开始处理
【INFO】2024-11-17 15:27:59,247 - cloudstrmcompanion - /test 目录树下载成功
【INFO】2024-11-17 15:27:55,727 - cloudstrmcompanion - 等待目录树生成完成，剩余重试 59 次
【INFO】2024-11-17 15:27:55,429 - cloudstrmcompanion - 开始生成 /test 目录树
【INFO】2024-11-17 15:27:55,428 - cloudstrmcompanion - 云盘Strm助手同步生成任务开始
【INFO】2024-11-17 15:27:52,426 - cloudstrmcompanion - 云盘Strm助手全量执行服务启动，立即运行一次
【INFO】2024-11-17 15:27:52,425 - cloudstrmcompanion - /cd2/CloudDrive/115k/test 的Strm生成实时监控服务启动
【INFO】2024-11-17 15:27:52,415 - cloudstrmcompanion - 旧数据索引清理完成
【INFO】2024-11-17 15:27:52,413 - cloudstrmcompanion - 开始清理旧数据索引
【INFO】2024-11-17 15:27:28,200 - cloudstrmcompanion - /cd2/CloudDrive/115k/test 的Strm生成实时监控服务启动

**Comment by qqcomeup** [comment]
> 更新 ----
![QQ截图20241117163431](https://github.com/user-attachments/assets/26d18a70-fa73-4743-ac18-b0c044a30631)
已是最新版
V1.1.5!

**Comment by GGbond1680** [comment]
这个问题我也有
<img width="1503" alt="image" src="https://github.com/user-attachments/assets/daf7f7a4-eb15-4a23-a3e2-131d411f0111">
一直在处理消息

**Comment by thsrite** [comment]
看主程序日志报错了吗？

**Comment by qqcomeup** [comment]
> 看主程序日志报错了吗？

MP开了开发者日志，立马运行插件，不确定是否这个日志
【INFO】2024-11-17 18:23:05,488 - transfer.py - 没有已完成下载但未整理的任务
【DEBUG】2024-11-17 18:23:31,424 - event.py - Enabled event handler class - app.plugins.cloudstrmcompanion.CloudStrmCompanion
【DEBUG】2024-11-17 18:23:31,427 - command.py - Acquired lock for initializing commands in background.
【DEBUG】2024-11-17 18:23:31,436 - event.py - Triggering synchronous chain event: <Chain Event: command.register, ID: bddb4a6b-a675-4eca-a92a-2e39564de53c, Priority: 10>
【DEBUG】2024-11-17 18:23:31,438 - event.py - No handlers found for chain event: <Chain Event: command.register, ID: bddb4a6b-a675-4eca-a92a-2e39564de53c, Priority: 10>
【DEBUG】2024-11-17 18:23:31,439 - command.py - Registering initial command count: 25
【DEBUG】2024-11-17 18:23:31,439 - command.py - Command set unchanged, skipping broadcast registration.

插件日志也是一直重新通知。
INFO:    cloudstrmcompanion - 开始写入本地文件 /config/plugins/CloudStrmCompanion/cloud_files.json
INFO:    cloudstrmcompanion - 云盘Strm助手同步生成任务完成
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
INFO:     192.168.8.51:0 - "GET /api/v1/system/logging?length=-1&logfile=plugins/cloudstrmcompanion.log HTTP/1.1" 200 OK
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
INFO:     192.168.8.51:0 - "GET /api/v1/system/logging?length=-1&logfile=plugins/cloudstrmcompanion.log HTTP/1.1" 200 OK
INFO:     192.168.8.51:0 - "GET /api/v1/system/logging?length=-1 HTTP/1.1" 200 OK
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
INFO:     192.168.8.51:0 - "GET /api/v1/system/logging?length=-1 HTTP/1.1" 200 OK
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息
INFO:     192.168.8.51:0 - "GET /api/v1/system/logging?length=-1 HTTP/1.1" 200 OK
跳过 3 条记录
INFO:    cloudstrmcompanion - 开始处理媒体 龙的传人 (1991) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 叛军岭 (2024) 消息
INFO:    cloudstrmcompanion - 开始处理媒体 爆款好人 (2024) 消息

**Comment by thsrite** [comment]
1.1.6已修
