### ISSUE TITLE
云盘strm生成插件，已有新文件但没有监控并生成

### ISSUE THREAD

**Issue by lutian98** [thsrite/MoviePilot-Plugins#14]
MP版本：1.5.9-1
插件版本：2.2
插件配置：compatibility#/mnt/user/CloudNAS/clouddrive/CloudDrive/115/AdultVideo/JAV_output#/mnt/user/Media/Jav/strm#cd2#/mnt/user/CloudNAS/clouddrive/CloudDrive#192.168.3.197:19798
复制非媒体文件已打开

问题描述：
监控目录内，24小时前已新增视频文件，但插件并没有在目的目录生成对应的strm文件，怀疑监控失效；
MP版本1.5.6、插件版本1.7，监控正常运行，一般一个晚上后就能看到目的目录新生成的strm文件；
尝试立即运行一次后，目的目录能生成新的对应的strm文件。

**Comment by lutian98** [comment]
今天好像又正常了

**Comment by 7-orion** [comment]
+1 我也碰到同样的情况不知道如何解决
