### ISSUE TITLE
大佬，是否可以给一个cd2的strm创建模板呢？

### ISSUE THREAD

**Issue by Whys8182** [thsrite/MoviePilot-Plugins#140]
大佬，是否可以给一个cd2的strm创建模板呢？虽然看懂了挂载本地的strm网盘链接生成，但是cd2的，始终肝不出来怎么配置。readme里面也没有具体写出来。

**Comment by thsrite** [comment]
助手插件页面写了

**Comment by Whys8182** [comment]
但是cd2还是不清楚，需要有个例子，已经挂载到本地的那种，倒是有例子。拜托大佬了
