### ISSUE TITLE
插件市场找不到clouddrive2助手

### ISSUE THREAD

**Issue by mting1117** [thsrite/MoviePilot-Plugins#141]
大佬请问mp v2的插件市场找不到插件clouddrive2助手，可能是什么原因，从来没有安装过

![Screenshot_20241118_203722_kito Browser](https://github.com/user-attachments/assets/d17cb7fc-5c89-41c0-8806-8bf059fd11d6)
![Screenshot_20241118_203729_kito Browser](https://github.com/user-attachments/assets/c5d82460-6e06-49fc-bf17-f54a31b0fb60)

**Comment by thsrite** [comment]
安装强制卸载插件
看看里面有没有cd2助手插件，强制卸载掉

插件市场重新安装，安装不成功就进docker命令行手动安装依赖  pip install clouddrive

**Comment by mting1117** [comment]
> 安装强制卸载插件 看看里面有没有cd2助手插件，强制卸载掉
> 
> 插件市场重新安装，安装不成功就进docker命令行手动安装依赖 pip install clouddrive

有一个插件叫“插件彻底卸载”，但列表中没有cd2助手，那直接进行步骤2吗，“安装依赖 pip install clouddrive”

**Comment by thsrite** [comment]
> > 安装强制卸载插件 看看里面有没有cd2助手插件，强制卸载掉
> > 插件市场重新安装，安装不成功就进docker命令行手动安装依赖 pip install clouddrive
> 
> 有一个插件叫“插件彻底卸载”，但列表中没有cd2助手，那直接进行步骤2吗，“安装依赖 pip install clouddrive”

可以  然后安装插件重装重载插件，看看有没有cd2助手 重装/重载下
