### ISSUE TITLE
运行 Emby元数据刷新报错，请看下

### ISSUE THREAD

**Issue by 1647561692** [thsrite/MoviePilot-Plugins#143]
新建的mp-v2版本，没用那个迁移工具，手动重新将下载文件重新识别了i下，发现emby里面有一堆meta信息缺少的，就想用这个全都在处理一遍，运行报错
报错信息如下：

INFO:    embymetarefresh - 媒体库元数据刷新服务启动，立即运行一次
Pending jobs:
    媒体库元数据 (trigger: date[2024-11-19 11:33:53 CST], pending)
    媒体库元数据 (trigger: cron[month='*', day='*', day_of_week='*', hour='1', minute='5'], pending)
INFO:     10.0.3.1:0 - "PUT /api/v1/plugin/EmbyMetaRefresh HTTP/1.1" 200 OK
INFO:     10.0.3.1:0 - "GET /api/v1/plugin/?state=installed HTTP/1.1" 200 OK
INFO:    plugin.py - 共获取到 134 个线上插件
INFO:     10.0.3.1:0 - "GET /api/v1/plugin/?state=market HTTP/1.1" 200 OK
INFO:    embymetarefresh - 开始刷新媒体服务器 emby服务器 的媒体库元数据
INFO:    embymetarefresh - 开始刷新媒体库元数据，最近 5 天内入库媒体：356个
Job "媒体库元数据 (trigger: date[2024-11-19 11:33:53 CST], next run at: 2024-11-19 11:33:53 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/app/plugins/embymetarefresh/__init__.py", line 179, in refresh
    self.__refresh_emby(transferinfo, emby)
  File "/app/app/plugins/embymetarefresh/__init__.py", line 723, in __refresh_emby
    episode = int(transferinfo.episodes.replace("E", ""))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '29-30'
<img width="994" alt="image" src="https://github.com/user-attachments/assets/32288982-4c42-41ee-b6fa-c4ccb378a83e">

**Comment by 1647561692** [comment]
我用其他方法在emby里面手动把缺的元数据重新整理了

**Comment by thsrite** [comment]
mp历史记录里面有个集数是29-30的？ 为何？  把29和30集合并成一个视频了？

**Comment by thsrite** [comment]
emby里找到这个视频，右击--编辑元数据，看看集编号是29还是30还是29-30
![image](https://github.com/user-attachments/assets/e0912c4f-7c4f-4650-9b78-5a1664dfd51a)

**Comment by 1647561692** [comment]
确实有这样的。。。
<img width="1909" alt="image" src="https://github.com/user-attachments/assets/9e3d803e-fac0-46f3-a460-dfa6ee7e1b5c">
<img width="2092" alt="image" src="https://github.com/user-attachments/assets/976cb95c-d8c7-456d-a3df-7be8a916fa04">
是这个原因导致的啊，那我把这个删掉吧。这好像很久以前不知道干啥下载的动画，现在不看了😵

**Comment by 1647561692** [comment]
issue关了

**Comment by thsrite** [comment]
v2  2.1.4兼容处理了
