### ISSUE TITLE
“插件彻底卸载”插件中，缺少插件

### ISSUE THREAD

**Issue by Whys8182** [thsrite/MoviePilot-Plugins#150]
“插件彻底卸载”插件中，缺少插件“Strm重定向”

**Comment by thsrite** [comment]
安装后才会在“插件彻底卸载”插件中显示
如未显示 是安装插件问题

**Comment by Whys8182** [comment]
这俩插件署名都是佬，你自己开发的插件，应该是你没有适配吧？

**Comment by Whys8182** [comment]
另一个更新的插件倒是有”Strm重定向“，不过更新插件，也有个特别的问题，就是已经卸载的插件，也会显示在“插件更新管理”插件列表里；至于插件卸载的这个插件，应该是没有加上“Strm重定向”插件
