### ISSUE TITLE
自动备份插件每次更新后都自动降级到1.3的版本 

### ISSUE THREAD

**Issue by felix-klk** [thsrite/MoviePilot-Plugins#151]
![image](https://github.com/user-attachments/assets/e949c4a3-2d94-4d18-b9a6-8f53bc53b892)
这个问题是什么导致的尼  用过卸载重装插件卸载过也不行

**Comment by thsrite** [comment]
用的老镜像？ 更新镜像

**Comment by felix-klk** [comment]
> 用的老镜像？ 更新镜像

不是更新每次 都是拉取的最新镜像

**Comment by felix-klk** [comment]
> 用的老镜像？ 更新镜像

![image](https://github.com/user-attachments/assets/cbd74076-5952-463f-9f61-4b02c3c5f789)

**Comment by thsrite** [comment]
官方插件库问题  已pr 等merge
