### ISSUE TITLE
观影报告不推送图片

### ISSUE THREAD

**Issue by lizimeng996** [thsrite/MoviePilot-Plugins#154]
您好T佬，我的mp和观影报告插件都是最新版本，我这里的现象是mp消息这里推送有图片，tg收到的推送无图，日志里也看不出有什么问题，请大佬帮忙看下。![image](https://github.com/user-attachments/assets/265ff2b1-af49-4961-872a-4c4c5ba4fb13)![image](https://github.com/user-attachments/assets/b96d7a0e-8dc0-4d67-83a2-84caa2264651)![image](https://github.com/user-attachments/assets/1b087688-5adf-4110-87cd-21ede5ef75c6)

**Comment by thsrite** [comment]
看主程序日志，tg发送消息的时候报错了吧

**Comment by lizimeng996** [comment]
我已经打开了debug日志，重新运行了插件，主程序实时日志里没有这个插件的相关日志

**Comment by thsrite** [comment]
![image](https://github.com/user-attachments/assets/e48a36f6-8569-4f4e-999f-9a5da97bcca1)
这前后没报错？

**Comment by lizimeng996** [comment]
没有报错，主程序甚至都没相关日志，插件日志显示推送成功，主程序日志没有相关内容![image](https://github.com/user-attachments/assets/9059236c-163a-4225-a6ca-5bdfb60bf0f3)![image](https://github.com/user-attachments/assets/75f5c27c-a36e-4c4b-ae1e-d47bf4211aaf)

**Comment by thsrite** [comment]
请截图主程序日志，参考我发的

**Comment by lizimeng996** [comment]
刚才已截图 可能是没加载出来，已重新截图
<img width="731" alt="sysytem" src="https://github.com/user-attachments/assets/5f8e9d2d-03ae-4cb6-8394-864be83f832e">

**Comment by thsrite** [comment]
https://github.com/thsrite/MoviePilot-Plugins/issues/154#issuecomment-2499904673

请参考我发的谢谢，你这日志我什么也看不出来

**Comment by lizimeng996** [comment]
我懂大佬的意思 但是这就是我运行插件时的主程序日志，没有关于插件的相关内容，已经开了debug模式了

**Comment by thsrite** [comment]
那不可能的。 你好好找找吧。

**Comment by lizimeng996** [comment]
在docker容器的日志里找到了 ，推送成功后面的url是有图片和内容的
<img width="814" alt="插件" src="https://github.com/user-attachments/assets/f5128a68-b255-444a-b7ed-377d3a557388">

**Comment by thsrite** [comment]
在家里  连得家里wifi？  网络问题导致的tg看不到图

**Comment by thsrite** [comment]
你可以把插件里的MoviePilot域名改成外网地址试下

**Comment by lizimeng996** [comment]
wifi和流量都试过，我是在nas上部署了openvpen服务，通过连接openvpn访问家里nas的，路由器端口只转发了openvpn服务的端口。域名之前改成我的域名也不行。会不会因为我路由器的端口转发从tcp改为udp的原因呢。我现在媒体库的入库信息和播放信息也没法推送，之前这些信息都是能正常推送的.观影记录也有图片。

**Comment by thsrite** [comment]
那是你网络问题，与插件无关了
