### ISSUE TITLE
目录实时监控插件缺失一个一级分类？

### ISSUE THREAD

**Issue by mosu14121** [thsrite/MoviePilot-Plugins#157]
就是如果使用目录实时监控插件，不点开二级分类的话，他会把全部文件硬链接到媒体库，不会分出“电影”“电视剧”这样的类别，然后点开二级分类的话，他就会变成“外国电影”“国产电视剧”这样的二级分类了，请问是否可以增加一个“电影”“电视剧”这样的一级分类的选项呢？

**Comment by thsrite** [comment]
监控目录写到一级分类
