### ISSUE TITLE
云盘删除插件  未连同文件夹一起删除

### ISSUE THREAD

**Issue by wanpijun2** [thsrite/MoviePilot-Plugins#158]
作者大大你好  云盘删除 插件 V2 版本 ，正常运行 可以同步删除，但是 没有连带文件夹一起删除 导致网盘里 文件夹和里面的图片还在， 能否改成和V1版一样 连带文件夹一起删除   辛苦了 作者大大
![image](https://github.com/user-attachments/assets/6f22505e-aff4-43f7-a081-6cc831804ef9)
![image](https://github.com/user-attachments/assets/0e3a8293-f090-4b25-9050-ad4aed965314)
![image](https://github.com/user-attachments/assets/2dd2f653-640e-4c58-9705-ef1c5b1cb819)

**Comment by wanpijun2** [comment]
还有就是 通知 不发送  删除记录 也没有  辛苦了大大
![image](https://github.com/user-attachments/assets/50b1479e-e18d-44a9-bf4e-c06ad4122d90)

**Comment by thsrite** [comment]
1.配置不对
2.截图截全
3.截图插件配置

**Comment by wanpijun2** [comment]
![image](https://github.com/user-attachments/assets/08b2f6b6-0ea7-4efe-9892-0e0bebc77157)
![image](https://github.com/user-attachments/assets/8a095178-481a-4c19-a3bb-e06921bd086f)
我的 V1  版就是这么配置的  你看下 大大

**Comment by thsrite** [comment]
![image](https://github.com/user-attachments/assets/0a9215d7-d60e-4adc-a0d5-172c20adda81)
只删除云盘文件的话 这块配置删除

**Comment by wanpijun2** [comment]
> ![image](https://private-user-images.githubusercontent.com/54088512/390283386-0a9215d7-d60e-4adc-a0d5-172c20adda81.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2ODc4OTAsIm5iZiI6MTczMjY4NzU5MCwicGF0aCI6Ii81NDA4ODUxMi8zOTAyODMzODYtMGE5MjE1ZDctZDYwZS00YWRjLWEwZDUtMTcyYzIwYWRkYTgxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI3VDA2MDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0ODQwZDIxZDllMmRkMDg0ZGY2Yzk4NDQ2NDc3MzI5YTE5ZWE1MmY5YTkwY2Y5MTljZjNmZTZjMTcyZTMyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.s3n9hOyAzvrT_WSoyHO-bgmh2wacuZhD5vtVLGAw_sQ)只删除云盘文件的话 这块配置删除

我试过 第二项不填 他文件夹还是 不删

**Comment by thsrite** [comment]
第二项不填，删除后给我完整插件日志

**Comment by wanpijun2** [comment]
![image](https://github.com/user-attachments/assets/b8865151-a29c-41a4-b0f3-534649aa80b3)
![image](https://github.com/user-attachments/assets/8f0b1d68-9f60-4310-872a-343473b825a0)
老大 你看下 好像 我找到原因了 是 另一个 插件 老是再删除完又创建了一个   我这是正常的对吧

**Comment by thsrite** [comment]
最新版删除文件夹了

**Comment by wanpijun2** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/162043360/390286843-b8865151-a29c-41a4-b0f3-534649aa80b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjM1MDEsIm5iZiI6MTczMzMyMzIwMSwicGF0aCI6Ii8xNjIwNDMzNjAvMzkwMjg2ODQzLWI4ODY1MTUxLWEyOWMtNDFhNC1iMGYzLTUzNDY0OWFhODBiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNDQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGZjMDVmNGRhOTAzYjkwOThjNDkzODU1ZTBkOGVmYjM1Yzc1NDFlODhlMTg3YzA3MWY4ODU3ZjFlNGFlYzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PXuAvbHRn2_vAdnx-4GRPgZ9UUwNrOCvfVmbZkpjTT8) ![图像](https://private-user-images.githubusercontent.com/162043360/390286894-8f0b1d68-9f60-4310-872a-343473b825a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjM1MDEsIm5iZiI6MTczMzMyMzIwMSwicGF0aCI6Ii8xNjIwNDMzNjAvMzkwMjg2ODk0LThmMGIxZDY4LTlmNjAtNDMxMC04NzJhLTM0MzQ3M2I4MjVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNDQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2I4OTA5NWE1MjNiOTRjNDhkMjIwNTMxOWM4ZTAwZGFlODczZTBkMDA2NWVhMDZhYjA4MDBkMjVlZTQzMTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XkUGSR4Yzri-DAFGRo8mvip3sDZAigH-iaAplWZz2dY)老大 你看下 好像 我找到原因了 是 另一个 插件 老是再删除完又创建了一个 我这是正常的对吧
> 
> 你好，你这个问题解决了吗？我也是这个问题，改了好多设置也是不删除文件夹

解决了 你看楼上 有图的 和 作者的回复 设置

**Comment by buqingchua** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/162043360/390286843-b8865151-a29c-41a4-b0f3-534649aa80b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjM1MDEsIm5iZiI6MTczMzMyMzIwMSwicGF0aCI6Ii8xNjIwNDMzNjAvMzkwMjg2ODQzLWI4ODY1MTUxLWEyOWMtNDFhNC1iMGYzLTUzNDY0OWFhODBiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNDQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGZjMDVmNGRhOTAzYjkwOThjNDkzODU1ZTBkOGVmYjM1Yzc1NDFlODhlMTg3YzA3MWY4ODU3ZjFlNGFlYzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PXuAvbHRn2_vAdnx-4GRPgZ9UUwNrOCvfVmbZkpjTT8) ![图像](https://private-user-images.githubusercontent.com/162043360/390286894-8f0b1d68-9f60-4310-872a-343473b825a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjM1MDEsIm5iZiI6MTczMzMyMzIwMSwicGF0aCI6Ii8xNjIwNDMzNjAvMzkwMjg2ODk0LThmMGIxZDY4LTlmNjAtNDMxMC04NzJhLTM0MzQ3M2I4MjVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNDQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2I4OTA5NWE1MjNiOTRjNDhkMjIwNTMxOWM4ZTAwZGFlODczZTBkMDA2NWVhMDZhYjA4MDBkMjVlZTQzMTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XkUGSR4Yzri-DAFGRo8mvip3sDZAigH-iaAplWZz2dY)老大 你看下 好像 我找到原因了 是 另一个 插件 老是再删除完又创建了一个 我这是正常的对吧
> > 
> > 
> > 你好，你这个问题解决了吗？我也是这个问题，改了好多设置也是不删除文件夹
> 
> 解决了 你看楼上 有图的 和 作者的回复 设置

你好，我也是第二项没填，刚测试还是不删除文件夹，哪里还需要设置吗？

**Comment by wanpijun2** [comment]
> > > > ![图像](https://private-user-images.githubusercontent.com/162043360/390286843-b8865151-a29c-41a4-b0f3-534649aa80b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjM1MDEsIm5iZiI6MTczMzMyMzIwMSwicGF0aCI6Ii8xNjIwNDMzNjAvMzkwMjg2ODQzLWI4ODY1MTUxLWEyOWMtNDFhNC1iMGYzLTUzNDY0OWFhODBiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNDQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGZjMDVmNGRhOTAzYjkwOThjNDkzODU1ZTBkOGVmYjM1Yzc1NDFlODhlMTg3YzA3MWY4ODU3ZjFlNGFlYzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PXuAvbHRn2_vAdnx-4GRPgZ9UUwNrOCvfVmbZkpjTT8) ![图像](https://private-user-images.githubusercontent.com/162043360/390286894-8f0b1d68-9f60-4310-872a-343473b825a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjM1MDEsIm5iZiI6MTczMzMyMzIwMSwicGF0aCI6Ii8xNjIwNDMzNjAvMzkwMjg2ODk0LThmMGIxZDY4LTlmNjAtNDMxMC04NzJhLTM0MzQ3M2I4MjVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNDQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2I4OTA5NWE1MjNiOTRjNDhkMjIwNTMxOWM4ZTAwZGFlODczZTBkMDA2NWVhMDZhYjA4MDBkMjVlZTQzMTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XkUGSR4Yzri-DAFGRo8mvip3sDZAigH-iaAplWZz2dY)老大 你看下 好像 我找到原因了 是 另一个 插件 老是再删除完又创建了一个 我这是正常的对吧
> > > 
> > > 
> > > 你好，你这个问题解决了吗？我也是这个问题，改了好多设置也是不删除文件夹
> > 
> > 
> > 解决了 你看楼上 有图的 和 作者的回复 设置
> 
> 你好，我也是第二项没填，刚测试还是不删除文件夹，哪里还需要设置吗？

排除 路径 要填 才能命中  云盘删除插件 启动

**Comment by buqingchua** [comment]
> > > > > ![图像](https://private-user-images.githubusercontent.com/162043360/390286843-b8865151-a29c-41a4-b0f3-534649aa80b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjM1MDEsIm5iZiI6MTczMzMyMzIwMSwicGF0aCI6Ii8xNjIwNDMzNjAvMzkwMjg2ODQzLWI4ODY1MTUxLWEyOWMtNDFhNC1iMGYzLTUzNDY0OWFhODBiMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNDQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGZjMDVmNGRhOTAzYjkwOThjNDkzODU1ZTBkOGVmYjM1Yzc1NDFlODhlMTg3YzA3MWY4ODU3ZjFlNGFlYzk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.PXuAvbHRn2_vAdnx-4GRPgZ9UUwNrOCvfVmbZkpjTT8) ![图像](https://private-user-images.githubusercontent.com/162043360/390286894-8f0b1d68-9f60-4310-872a-343473b825a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMjM1MDEsIm5iZiI6MTczMzMyMzIwMSwicGF0aCI6Ii8xNjIwNDMzNjAvMzkwMjg2ODk0LThmMGIxZDY4LTlmNjAtNDMxMC04NzJhLTM0MzQ3M2I4MjVhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwNFQxNDQwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hM2I4OTA5NWE1MjNiOTRjNDhkMjIwNTMxOWM4ZTAwZGFlODczZTBkMDA2NWVhMDZhYjA4MDBkMjVlZTQzMTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XkUGSR4Yzri-DAFGRo8mvip3sDZAigH-iaAplWZz2dY)老大 你看下 好像 我找到原因了 是 另一个 插件 老是再删除完又创建了一个 我这是正常的对吧
> > > > 
> > > > 
> > > > 你好，你这个问题解决了吗？我也是这个问题，改了好多设置也是不删除文件夹
> > > 
> > > 
> > > 解决了 你看楼上 有图的 和 作者的回复 设置
> > 
> > 
> > 你好，我也是第二项没填，刚测试还是不删除文件夹，哪里还需要设置吗？
> 
> 排除 路径 要填 才能命中 云盘删除插件 启动

排除路径也填了，可以删除视频文件，但是没有删除放视频文件的文件夹
