### ISSUE TITLE
目录实时监控2.5.6，摩登家庭S06，识别成俄罗斯剧。

### ISSUE THREAD

**Issue by eaglexxxm** [thsrite/MoviePilot-Plugins#159]
摩登家庭S06.Modern.Family.2014.1080p.WEB-DL.x265.AC3￡cXcY@FRDS/Modern.Family.S06E01.2014.1080p.WEB-DL.x265.10bit.AC3￡cXcY@FRDS.mkv

> 【INFO】2024-11-27 21:58:59,622 - themoviedb - Μοντέρνα Οικογένεια TMDB识别结果：电视剧 Μοντέρνα Οικογένεια (2014) 102126
【INFO】2024-11-27 21:58:58,496 - themoviedb - 正在识别 Μοντέρνα Οικογένεια 第6季 ...
【INFO】2024-11-27 21:58:58,472 - media.py - 开始刮削：/downloads/data_link/电视剧/未分类/Μοντέρνα Οικογένεια (2014)/Season 6/Μοντέρνα Οικογένεια - S06E15 - 第 15 集.mkv ...
【INFO】2024-11-27 21:58:58,458 - media.py - 开始刮削：/downloads/data_link/电视剧/未分类/Μοντέρνα Οικογένεια (2014)/Season 6 ...
【INFO】2024-11-27 21:58:58,446 - media.py - 开始刮削：/downloads/data_link/电视剧/未分类/Μοντέρνα Οικογένεια (2014) ...
【INFO】2024-11-27 21:58:58,443 - filemanager - 文件 /downloads/video/tv/摩登家庭S01-S11.Modern.Family.2009-2019.1080p.WEB-DL.x265.AC3￡cXcY@FRDS/摩登家庭S06.Modern.Family.2014.1080p.WEB-DL.x265.AC3￡cXcY@FRDS/Modern.Family.S06E15.2014.1080p.WEB-DL.x265.10bit.AC3￡cXcY@FRDS.mkv 整理成功
【INFO】2024-11-27 21:58:58,439 - filemanager - /downloads/video/tv/摩登家庭S01-S11.Modern.Family.2009-2019.1080p.WEB-DL.x265.AC3￡cXcY@FRDS/摩登家庭S06.Modern.Family.2014.1080p.WEB-DL.x265.AC3￡cXcY@FRDS/ 目录下没有找到字幕文件...
【INFO】2024-11-27 21:58:58,291 - filemanager - 正在整理文件：【local】/downloads/video/tv/摩登家庭S01-S11.Modern.Family.2009-2019.1080p.WEB-DL.x265.AC3￡cXcY@FRDS/摩登家庭S06.Modern.Family.2014.1080p.WEB-DL.x265.AC3￡cXcY@FRDS/Modern.Family.S06E15.2014.1080p.WEB-DL.x265.10bit.AC3￡cXcY@FRDS.mkv 到 【local】/downloads/data_link/电视剧/未分类/Μοντέρνα Οικογένεια (2014)/Season 6/Μοντέρνα Οικογένεια - S06E15 - 第 15 集.mkv，操作类型：link
【INFO】2024-11-27 21:58:58,271 - filemanager - 获取整理目标路径：【local】/downloads/data_link/电视剧/未分类
【ERROR】2024-11-27 21:58:58,260 - tmdbapi.py - The resource you requested could not be found.
【INFO】2024-11-27 21:58:57,918 - cloudlinkmonitor - Modern.Family.S06E15.2014.1080p.WEB-DL.x265.10bit.AC3￡cXcY@FRDS.mkv 识别为：电视剧 Μοντέρνα Οικογένεια (2014)
【INFO】2024-11-27 21:58:57,233 - themoviedb - Modern Family TMDB识别结果：电视剧 Μοντέρνα Οικογένεια (2014) 102126
【INFO】2024-11-27 21:58:57,218 - themoviedb - 正在识别 Modern Family 第6季 ...
【INFO】2024-11-27 21:58:57,171 - cloudlinkmonitor - 开始处理文件 /downloads/video/tv/摩登家庭S01-S11.Modern.Family.2009-2019.1080p.WEB-DL.x265.AC3￡cXcY@FRDS/摩登家庭S06.Modern.Family.2014.1080p.WEB-DL.x265.AC3￡cXcY@FRDS/Modern.Family.S06E15.2014.1080p.WEB-DL.x265.10bit.AC3￡cXcY@FRDS.mkv ...

S06识别成俄罗斯剧？其他季没有问题。

**Comment by thsrite** [comment]
识别整理走的主程序的逻辑，你可以命名识别测试下
