### ISSUE TITLE
云盘 strm 助手的电报指令

### ISSUE THREAD

**Issue by mting1117** [thsrite/MoviePilot-Plugins#164]
/strm 动漫剧 8
我看之前您发的是处理第 8 个文件夹
今天测试日志是处理的前 8 个文件夹，是后续有调整吗
![Screenshot_20241204_230920_YJBrowser](https://github.com/user-attachments/assets/1bc4676b-7ccc-4105-9831-66d3547e5f7e)
![Screenshot_20241204_230935_Telegram](https://github.com/user-attachments/assets/3edeabb7-8774-4b5e-84b0-0ca4674b062f)

**Comment by thsrite** [comment]
就是前8  要不你就指定名字
