### ISSUE TITLE
媒体同步删除插件

### ISSUE THREAD

**Issue by AutunnoLL** [thsrite/MoviePilot-Plugins#167]
希望路径映射适配emby位于windows环境下的情况，似乎目前win路径中的冒号会影响路径分割和替换

**Comment by AutunnoLL** [comment]
还有就是电视剧单独一集被删除时，emby发送的tmdb id似乎是不对的，与整个电视剧的tmdb id不一致，导致无法正确查找到历史记录。不知道是不是我这个emby有问题

**Comment by thsrite** [comment]
@AutunnoLL Webhook还是scripterx插件方式？webhook修不了得找luke，插件方式没问题

**Comment by AutunnoLL** [comment]
是用的webhook方式，插件方式没测试，但看源码似乎也会有问题。
win环境下装emby的话，路径映射那个地方会出现两个冒号，应该是影响了755行的分割。
tmdb id的问题暂时没用插件方式测试。

**Comment by AutunnoLL** [comment]
稍微修改了下暂时可以用了。
已关闭

**Comment by tclyg2008** [comment]
您好，我也是windows，请问怎么设置，我也用webhook，设置为没反应，还想麻烦您指教。
我emby里面webhook的url写的是：http://192.168.31.100:3000/api/v1/webhook?token=API_TOKEN
我插件里面路径映射是留空的。（因为路径应该是一样的）

**Comment by tclyg2008** [comment]
> 稍微修改了下暂时可以用了。 已关闭

您好，我也是windows，请问怎么设置，我也用webhook，设置为没反应，还想麻烦您指教。
我emby里面webhook的url写的是：http://192.168.31.100:3000/api/v1/webhook?token=API_TOKEN
我插件里面路径映射是留空的。（因为路径应该是一样的）
