### ISSUE TITLE
目录实时监控的文件覆盖方式

### ISSUE THREAD

**Issue by mting1117** [thsrite/MoviePilot-Plugins#169]
大佬，请教一个问题，整理时按文件大小覆盖，对于同名资源但后缀不一样的，比如 mkv 和 mp4， 不会按这个设定走，整理后会共存，正常吗

**Comment by thsrite** [comment]
完全同名即同名+同后缀才会覆盖，具体有问题，请去主程序提。插件走的主程序的转移逻辑
