### ISSUE TITLE
订阅规则自动填充关于杜比视界的规则填充问题

### ISSUE THREAD

**Issue by ShawsFOR** [thsrite/MoviePilot-Plugins#171]
我在订阅下载后，发现关于杜比视界的资源有如下情况（有附图）：
1、基础信息中，特效下拉菜单中为”杜比视界”，但是插件填充为“DoVi”
2、进阶的包含（关键词、正则）中，填充的也是“DoVi”，但实际标题中是“DV"

我看到后都人工修改了，不知道这是否是一个适配的问题？还是v2中DoVi会自动匹配为杜比视界和DV？
![photo_2024-12-09_17-51-13](https://github.com/user-attachments/assets/470f102f-d638-40b5-9420-c6ba400eb2ab)
![photo_2024-12-09_17-51-10](https://github.com/user-attachments/assets/0746fbf4-57df-4601-b00a-0a02f692ba22)
![photo_2024-12-09_17-52-17](https://github.com/user-attachments/assets/d72b34b0-4765-4602-8f1a-1395b5dec441)

**Comment by NASA0719** [comment]
`(?<=[\W_])DV(?=[\W_]) => DoVi`
这条自定义识别词的原因吧

**Comment by ShawsFOR** [comment]
看起来像是，布丁佬的公共词表里的。。那就是这条会对规则自动填充产生干扰？在 2024年12月9日，21:38，NASA0719 ***@***.***> 写道：﻿
(?<=[\W_])DV(?=[\W_]) => DoVi
这条自定义识别词的原因吧

**Comment by thsrite** [comment]
v2.8.3
