### ISSUE TITLE
目录实时监控 未能吃到 V2 的覆盖模式配置

### ISSUE THREAD

**Issue by wanpijun2** [thsrite/MoviePilot-Plugins#172]
作者 大大  插件 没有吃到 V2 目录设置的   按大小模式覆盖     这项设置 ，    导致 我加入了替换内容 没有覆盖影片 ，查看日志插件的 覆盖模式是: 从不  
<img width="1687" alt="1733854354883" src="https://github.com/user-attachments/assets/a7fe6ff4-b0d8-4b9b-ab40-42492c25b3ae">

**Comment by wanpijun2** [comment]
比如 我上传了一部比之前更好的资源    他不会去覆盖 提示 覆盖模式为不覆盖

**Comment by thsrite** [comment]
![image](https://github.com/user-attachments/assets/cf8368f7-349e-4158-93c0-ad2449f9af49)

**Comment by wanpijun2** [comment]
> ![image](https://private-user-images.githubusercontent.com/54088512/394997932-cf8368f7-349e-4158-93c0-ad2449f9af49.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NzQ3MTYsIm5iZiI6MTczMzk3NDQxNiwicGF0aCI6Ii81NDA4ODUxMi8zOTQ5OTc5MzItY2Y4MzY4ZjctMzQ5ZS00MTU4LTkzYzAtYWQyNDQ5ZjlhZjQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjEyVDAzMzMzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMGRmYWE0OGJhMzFlMGI4ZTE0Y2FkNzNhYjkwYzNmM2U1M2MxNjc5N2Q3ODZjNzk2MzcyZTUyNjVkNGRmOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rFccfz6Sr7vFPz9ERqkx8CejVivMZbgXsVEiMl-lwXU)
<img width="728" alt="1733974449930" src="https://github.com/user-attachments/assets/c09ccfd5-782d-4b37-9b24-44e6fbf07630" />
wo'jia'l我加了 老大 我的意思 是 覆盖模式 就是 按大小覆盖 把上一个 替换掉

**Comment by thsrite** [comment]
你哪里设置的按大小覆盖啊   你在配置最后加个@size

**Comment by thsrite** [comment]
@size

**Comment by thsrite** [comment]
你哪里设置的按大小覆盖啊 ，你在配置那一行最后加个`@size`

**Comment by wanpijun2** [comment]
> @SiZe
<img width="755" alt="1733974644109" src="https://github.com/user-attachments/assets/20e2b4cb-0e60-4cee-8677-0e08b5656a9b" />
这样么  老大

**Comment by thsrite** [comment]
小写

**Comment by wanpijun2** [comment]
好的 感谢  老大 

> 小写
