### ISSUE TITLE
云盘Strm助手复制非媒体文件功能貌似无效

### ISSUE THREAD

**Issue by yellowstrong** [thsrite/MoviePilot-Plugins#174]
![longshot20241211200720](https://github.com/user-attachments/assets/6213a5e5-2c90-44fc-8f7c-2ba0517c672b)
![longshot20241211200837](https://github.com/user-attachments/assets/e685a40f-260b-4b8b-a86a-a269651f395f)
![longshot20241211200903](https://github.com/user-attachments/assets/d5af32dd-a455-4673-bee3-6c4c9d11555d)
如图，这部剧的nfo,jpg文件均未被复制或者链接到目标文件夹

**Comment by yellowstrong** [comment]
![longshot20241211210936](https://github.com/user-attachments/assets/08a228ec-a1fe-4b85-8e3c-305eae036016)
并且每次启动都会在这里卡很久 大佬知道为什么嘛

**Comment by yellowstrong** [comment]
![longshot20241212110139](https://github.com/user-attachments/assets/c1a71973-66d7-4682-8aca-63f374f1da98)
只要勾了实时监控，这个界面保存就会卡很久很久

**Comment by thsrite** [comment]
v1.2.2
