### ISSUE TITLE
目录实时监控v2.5.6 移动方式会删除监控目录

### ISSUE THREAD

**Issue by dalamudx** [thsrite/MoviePilot-Plugins#175]
感觉这个问题出现一段时间了，至少上个月就有这个问题，移动的时候，会删除监控目录，比如我这里设置movies和tvs两个文件夹
![image](https://github.com/user-attachments/assets/15108867-685e-4425-aad2-1a97c86ebcde)
目前发现是会随机删除tvs或者movies文件夹，前几天tvs删掉了我手动创建好，今天发现movies又被删掉了
![image](https://github.com/user-attachments/assets/8c30b6e0-bdeb-46a7-bbb3-a457b58a9786)
不清楚是插件bug还是主程序的就先发这里

**Comment by thsrite** [comment]
提供下删除文件夹的日志

**Comment by dalamudx** [comment]
看起来是主程序的问题，有fix，暂时没发现误删了，问题先关闭再观察下
