### ISSUE TITLE
云盘Strm助手的strm生成命令

### ISSUE THREAD

**Issue by SchrodingerBarbatos** [thsrite/MoviePilot-Plugins#176]
这是两个监控目录:
/volume1/CloudNAS/CloudDrive/115/emby/anime#/strm/anime#/emby/anime#{local_file}@国漫,美漫,外语电影,日番,日韩剧$nomonitor
/volume1/CloudNAS/CloudDrive/115/emby/tv#/strm/tv#/emby/tv#{local_file}@欧美剧,日韩剧,国产剧$nomonitor

文件目录是:
/volume1/CloudNAS/CloudDrive/115/emby/tv/日韩剧/住宅区的两人

日志为：
【INFO】2024-12-12 22:15:55,894 - cloudstrmcompanion - 开始检查 /volume1/CloudNAS/CloudDrive/115/emby/anime 国漫,美漫,外语电影,日番,日韩剧
INFO】2024-12-12 22:15:55,895 - cloudstrmcompanion - 获取到 日韩剧 住宅区的两人 对应的监控目录 /volume1/CloudNAS/CloudDrive/115/emby/anime/日韩剧
【INFO】2024-12-12 22:15:55,899 - cloudstrmcompanion - 开始处理 /volume1/CloudNAS/CloudDrive/115/emby/anime/日韩剧/住宅区的两人
【ERROR】2024-12-12 22:15:56,988 - cloudstrmcompanion - 未查找到 日韩剧 住宅区的两人 对应的具体目录

如果命令是/strm 日韩剧 住宅区的两人，只会按顺序检查到anime文件夹下的日韩剧目录，不会检查tv的日韩剧目录，能不能修改成全部检查，或者检查不到，继续往下检查，例如anime文件夹检查不到，再检查tv，直到所有目录结束

**Comment by thsrite** [comment]
改媒体库名吧，anime下有日韩剧合理么？ 不已经有了日番，你大不了加个韩漫
