### ISSUE TITLE
云盘文件删除 v1.3 请求支持MP-V2

### ISSUE THREAD

**Issue by rdself** [thsrite/MoviePilot-Plugins#178]
注意到从能同步处理Strm文件删除的“云盘文件删除 v1.3”并未支持v2，恳请加入对v2的支持，感谢！

另外一个思路供大佬参考：也可以在“媒体文件同步删除”插件中增加额外的一重映射，类似"emby docker下strm目录路径 => mp docker下strm目录路径 => mp docker下网盘挂载目录路径"，实现无论是Strm模式还是软链接模式，都可以直接同步删除云盘文件。

**Comment by thsrite** [comment]
@RogerProSelf 云盘同步删除插件
