### ISSUE TITLE
目录 转移失败运行模块出错  

### ISSUE THREAD

**Issue by wanpijun2** [thsrite/MoviePilot-Plugins#180]
【INFO】2024-12-17 13:34:42,394 - cloudlinkmonitor - 全量同步云盘实时监控目录完成！
【ERROR】2024-12-17 13:34:42,394 - cloudlinkmonitor - 文件转移模块运行失败

FileNotFoundError: [Errno 2] No such file or directory: '/volume2/CloudNAS/CloudDrive/115/影视库/国产剧/清明上河图密码 (2024)'
    os.mkdir(self, mode)
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    self.mkdir(mode, parents=False, exist_ok=exist_ok)
  File "/usr/local/lib/python3.11/pathlib.py", line 1121, in mkdir
    path.mkdir(parents=True, exist_ok=True)
  File "/app/app/modules/filemanager/storages/local.py", line 133, in get_folder
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    target_diritem = target_oper.get_folder(new_file.parents[rename_format_level - 1])
  File "/app/app/modules/filemanager/__init__.py", line 1019, in transfer_media
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return self.transfer_media(fileitem=fileitem,
  File "/app/app/modules/filemanager/__init__.py", line 407, in transfer
             ^^^^^^^^^^^^^^^^^^^^^
    result = func(*args, **kwargs)
  File "/app/app/chain/__init__.py", line 112, in run_module
Traceback (most recent call last):

During handling of the above exception, another exception occurred:

FileNotFoundError: [Errno 2] No such file or directory: '/volume2/CloudNAS/CloudDrive/115/影视库/国产剧/清明上河图密码 (2024)'
    os.mkdir(self, mode)
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
Traceback (most recent call last):
【ERROR】2024-12-17 13:34:42,392 - chain - 运行模块 FileManagerModule.transfer 出错：[Errno 2] No such file or directory: '/volume2/CloudNAS/CloudDrive/115/影视库/国产剧/清明上河图密码 (2024)'
【INFO】2024-12-17 13:34:40,476 - filemanager - 获取整理目标路径：【local】/volume2/CloudNAS/CloudDrive/115/影视库/国产剧
【INFO】2024-12-17 13:34:40,472 - cloudlinkmonitor - 清明上河图密码 S01E03 1080p.QHstudIo.mp4 识别为：电视剧 清明上河图密码 (2024)
【INFO】2024-12-17 13:34:40,472 - themoviedb - 清明上河图密码 TMDB识别结果：电视剧 清明上河图密码 (2024) 252904
【INFO】2024-12-17 13:34:40,469 - themoviedb - 清明上河图密码 使用TMDB识别缓存：清明上河图密码
【INFO】2024-12-17 13:34:40,174 - cloudlinkmonitor - 开始处理文件 /volume2/CloudNAS/CloudDrive/115/转存/清明上河图密码 (2024)/Season 1/清明上河图密码 S01E03 1080p.QHstudIo.mp4 ...
![image](https://github.com/user-attachments/assets/42a61d43-a09f-4bdc-ba99-c19a9ae20be4)

**Comment by wanpijun2** [comment]
以往都是好好的

**Comment by thsrite** [comment]
@wanpijun2 你去cd2  115目录下创建个文件夹试试，这不是mp的问题

**Comment by wanpijun2** [comment]
> @wanpijun2 你去cd2 115目录下创建个文件夹试试，这不是mp的问题

以往不是 自动创建的么 。。。

**Comment by thsrite** [comment]
@wanpijun2 cd2  115有问题，跟mp无关啊，能明白吗？
