### ISSUE TITLE
hdarea签到处理

### ISSUE THREAD

**Issue by mysll** [thsrite/MoviePilot-Plugins#181]
hdarea签到失败,需要适配一下,签到地址 https://hdarea.club/sign_in.php

**Comment by thsrite** [comment]
![image](https://github.com/user-attachments/assets/1f277bef-4189-4aea-8de3-7991966d4df8)

**Comment by mysll** [comment]
** html_res = RequestUtils(cookies=site_cookie,
                                ua=ua,
                                proxies=proxies
                                ).post_res(url="https://www.hdarea.club/sign_in.php", data=data)**
代码里的网址,加上www会跳转,不加是正常的
![image](https://github.com/user-attachments/assets/760f0044-4c88-443c-999e-bece120f06d9)
复制网址在浏览器里打开,打开后就是我上面的提示

**Comment by mysll** [comment]
@thsrite 
```
html_res = RequestUtils(cookies=site_cookie,
                                ua=ua,
                                proxies=proxies
                                ).post_res(url="https://www.hdarea.club/sign_in.php", data=data)
```
代码里的网址,加上www会跳转,不加是正常的,我直接在容器里改了下,去掉www就签到正常了
![image](https://github.com/user-attachments/assets/760f0044-4c88-443c-999e-bece120f06d9)
复制网址在浏览器里打开,打开后就是我上面的提示,
