### ISSUE TITLE
[错误报告]: v2.1.5_插件_订阅规则自动填充 插件异常 #3594

### ISSUE THREAD

**Issue by cyx222800** [thsrite/MoviePilot-Plugins#182]
昨天使用时发现插件失效，通过日志发现最后一次正确填充是12月12日，怀疑是因为版本更新导致的。

之前规则如下：
下载种子填充规则：
特效，资源质量，分辨率，工作组，站点
二级分类填充规则：
category:动画电影#resolution:2160p#include:国语|中字#savepath:/media/PT下载/动漫/{name}
category:外语电影#resolution:2160p#include:国语|中字#savepath:/media/PT下载/电影/{name}
category:华语电影#resolution:2160p#savepath:/media/PT下载/电影/{name}
category:日番#filter_groups:优先4K组#include:国语|中字#savepath:/media/PT下载/动漫/{name}
category:国漫#filter_groups:优先4K组#savepath:/media/PT下载/动漫/{name}
category:综艺,纪录片#filter_groups:优先4K组#savepath:/media/PT下载/综艺/{name}
category:国产剧#resolution:2160p#savepath:/media/PT下载/电视/{name}
category:欧美剧#resolution:2160p#include:国语|中字#savepath:/media/PT下载/电视/{name}
category:日韩剧,儿童#filter_groups:优先4K组#include:国语|中字#savepath:/media/PT下载/电视/{name}

经过排查：发现只要规则中包含resolution这一参数，就会导致二级分类规则填充失效，2160p改为4k问题依旧

后将规则改为：
下载种子填充规则：
特效，资源质量，工作组，站点
二级分类填充规则：
category:动画电影#filter_groups:动画电影#savepath:/media/PT下载/动漫/{name}
category:外语电影#filter_groups:外语电影#savepath:/media/PT下载/电影/{name}
category:华语电影#filter_groups:华语电影#savepath:/media/PT下载/电影/{name}
category:日番#filter_groups:日番#savepath:/media/PT下载/动漫/{name}
category:国漫#filter_groups:国漫#savepath:/media/PT下载/动漫/{name}
category:儿童#filter_groups:儿童#savepath:/media/PT下载/动漫/{name}
category:综艺,纪录片#filter_groups:综艺#savepath:/media/PT下载/综艺/{name}
category:国产剧#filter_groups:国产剧#savepath:/media/PT下载/电视/{name}
category:欧美剧#filter_groups:欧美剧#savepath:/media/PT下载/电视/{name}
category:日韩剧#filter_groups:日韩剧#savepath:/media/PT下载/电视/{name}

修改后，二级分类自动填充功能恢复正常，但是当订阅剧集并完成下载种子后，下载种子自动填充规则依然失效，并不能正确填充 工作组站点等信息

eg：规则组中只包含了：分辨率4k，国语，中字 三条规则。

怀疑是不是分辨率参数进行过调整导致了插件异常，希望大佬可以看看，救救这个灵魂插件

**Comment by dlovew** [comment]
说个可以迂回的办法，关闭分辨率填充，分辨率可以在filter_groups规则组里指定，其他如站点，规则组等功能可以正常填充

**Comment by cyx222800** [comment]
> 说个可以迂回的办法，关闭分辨率填充，分辨率可以在filter_groups规则组里指定，其他如站点，规则组等功能可以正常填充

是可以这样.我上面也提到了,  但是发现下载种子自动填充  失效了.  订阅剧集的时候,下载完种子不会自动填入对应的站点等信息

**Comment by cyx222800** [comment]
> 说个可以迂回的办法，关闭分辨率填充，分辨率可以在filter_groups规则组里指定，其他如站点，规则组等功能可以正常填充

其实站点等信息是为了尽可能保证所下载数据的一致性..所以不好提前写入规则组
