### ISSUE TITLE
[插件BUG报告] MP主程序版本V2.1.5,  媒体文件同步删除V1.8.7 插件会出现删除文件所在的整个文件夹

### ISSUE THREAD

**Issue by qhly2010** [thsrite/MoviePilot-Plugins#183]
MP的下载目录设置为：/volume2/Download-2/Meida  (所有种子都下载到这个目录）
MP硬连接刮削的目录为：/volume2/Download-2/Links
emby媒体库目录为:/volume2/Download-2/Links/电影

出现的问题：媒体文件同步删除V1.8.7 插件开启删除源文件，如果从pt下载的视频为单独的视频时（无文件夹），下载后的路径如 /volume2/Download-2/Media/Pegasus.2019.4K.WEB-DL.H264.AAC-TJUPT.mp4  ，当从emby删除这个电影时，此插件会同步删除Media文件夹，导致我整个Media的文件全部丢失；如果从pt下载的视频含有文件夹时，下载后的路径如 /volume2/Download-2/Media/Pegasus（2019）/Pegasus.2019.4K.WEB-DL.H264.AAC-TJUPT.mp4  ,当从emby删除这个电影时，此插件会同步删除 Pegasus（2019）文件夹，即插件会删除文件所在的文件夹

日志：`【DEBUG】2024-12-22 16:44:49,326 - tmdbapi.py - 575219 查询结果：飞驰人生
【DEBUG】2024-12-22 16:44:49,324 - tmdbapi.py - 正在查询TMDB电影：575219 ...
【DEBUG】2024-12-22 16:44:49,320 - chain - 请求模块执行：obtain_specific_image ...
【DEBUG】2024-12-22 16:44:48,334 - tmdbapi.py - 575219 查询结果：飞驰人生
【DEBUG】2024-12-22 16:44:48,332 - tmdbapi.py - 正在查询TMDB电影：575219 ...
【DEBUG】2024-12-22 16:44:48,328 - chain - 请求模块执行：obtain_specific_image ...
【INFO】2024-12-22 16:44:48,327 - mediasyncdel - 同步删除 电影 飞驰人生 (2019) 575219 完成！
【DEBUG】2024-12-22 16:44:48,325 - chain - 请求模块执行：delete_file ...
【WARNING】2024-12-22 16:44:48,323 - mediasyncdel - 删除残留空文件夹：【local】/volume2/Download-2/Media/
【DEBUG】2024-12-22 16:44:48,320 - chain - 请求模块执行：any_files ...
【DEBUG】2024-12-22 16:44:48,318 - chain - 请求模块执行：get_parent_item ...
【DEBUG】2024-12-22 16:44:47,998 - chain - 请求模块执行：delete_file ...
【INFO】2024-12-22 16:44:47,994 - mediasyncdel - 开始删除源文件 /volume2/Download-2/Media/Pegasus.2019.4K.WEB-DL.H264.AAC-TJUPT.mp4
【DEBUG】2024-12-22 16:44:47,992 - chain - 请求模块执行：delete_file ...
【INFO】2024-12-22 16:44:47,490 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-12-22 16:44:47,489 - mediasyncdel - 正在同步删除电影 飞驰人生 (2019) 575219`

不知道这个算不算bug，我所有pt下载的文件全部在Media文件夹，几千视频和文件被插件连带Meida文件夹全部删除了，测试了4个小时才找到是这个原因。

**Comment by thsrite** [comment]
v1.8.8  试试看   主程序方法改了

**Comment by qhly2010** [comment]
> v1.8.8 试试看 主程序方法改了

1.8.8 还是有一点小问题，如果media文件夹内含有其他非视频文件，这时emby删除视频的时候，同样会删除整个media文件夹，测试发现插件在删除视频后会查询当前文件夹内是否还存在其他媒体文件，如果没有就删除当前文件夹，那么当前文件夹内的其他文件也跟着被删除了，存在丢失其他数据的风险，如果能够精准删除就好了，一种下载下来就只有单独的视频，另外一种下载下来包含在文件夹内的视频。单独的视频就只删除视频，不再判断其他的，含文件夹的才判断有无其他媒体再执行是否删除

**Comment by thsrite** [comment]
@qhly2010 提供日志文件  不要直接粘贴日志   可读性太差

**Comment by qhly2010** [comment]
> @qhly2010 提供日志文件 不要直接粘贴日志 可读性太差

[log.txt](https://github.com/user-attachments/files/18228688/log.txt)

**Comment by thsrite** [comment]
再测下呢，我改了删除本地文件方法

**Comment by qhly2010** [comment]
> 再测下呢，我改了删除本地文件方法

测试了几个小时，发现还存在以下问题：
1.直接更新插件使用，emby删除文件后，media文件夹内不会删除视频文件
2.使用插件彻底卸载V1.2.1卸载媒体文件同步删除插件，重启MP后再安装媒体文件同步删除插件使用（不重启MP直接安装，无法进入插件设置界面），这个时候再使用插件会出现下面情况：
   2.1 NAS直接复制视频文件到media，然后在MP手动整理，emby删除文件后，会同步删除meida内的视频，不会删除media文件，media文件内含其他文件，测试时放了一个.FLAC文件
   2.2 NAS直接复制带文件夹的视频文件到media，然后在MP手动整理，emby删除文件后，会同步删除meida内的视频，但不会删除父文件夹且父文件夹为空，也不会删除media文件，media文件内含其他文件，测试时放了一个.FLAC文件
  2.3 NAS直接复制视频文件（或者带文件夹的视频）到media，此时在NAS操作修改Media内的视频文件名，然后在MP手动整理，emby删除文件后，后续就不会再同步删除meida内的视频，不会删除media文件，media文件内含其他文件，测试时放了一个.FLAC文件，如果要想自动删除，又得卸载插件，重启MP重新安装才行
3.使用插件彻底卸载V1.2.1卸载媒体文件同步删除插件时，显示的媒体文件同步删除插件版本为V1.7.1 ，实际为最新的V1.8.9，d打开卸载插件反应也比较慢，不清楚是插件彻底卸载V1.2.1的BUG，还是MP未删除媒体文件同步删除插件版本为V1.7.1,导致和V1.8.9混用了
  
![插件彻底卸载V1 2 1](https://github.com/user-attachments/assets/11828664-cd64-4d20-8a3d-ef9cd5049251)

以下是测试日志：
 >【INFO】2024-12-24 15:26:47,188 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-12-24 15:26:47,187 - mediasyncdel - 正在同步删除电影 惊心食人族：重生 (2022) 717728
【INFO】2024-12-24 15:25:25,969 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-12-24 15:25:25,967 - mediasyncdel - 正在同步删除电影 惊心食人族：重生 (2022) 717728
【INFO】2024-12-24 15:23:16,928 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-12-24 15:23:16,927 - mediasyncdel - 正在同步删除电影 飞驰人生 (2019) 575219
【INFO】2024-12-24 15:19:58,738 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-12-24 15:19:58,737 - mediasyncdel - 正在同步删除电影 誓不忘情 (1992) 261190
【INFO】2024-12-24 15:18:08,764 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-12-24 15:18:08,763 - mediasyncdel - 正在同步删除电影 飞驰人生 (2019) 575219
【INFO】2024-12-24 15:17:00,306 - mediasyncdel - 获取到 1 条转移记录，开始同步删除
【INFO】2024-12-24 15:17:00,304 - mediasyncdel - 正在同步删除电影 震撼擂台 (2024) 1406169
【DEBUG】2024-12-24 15:15:55,760 - event.py - Subscribed to broadcast event: downloadfile.deleted - app.plugins.mediasyncdel.MediaSyncDel.downloadfile_del_sync
【DEBUG】2024-12-24 15:15:55,725 - event.py - Subscribed to broadcast event: plugin.action - app.plugins.mediasyncdel.MediaSyncDel.sync_del
【DEBUG】2024-12-24 15:15:55,685 - event.py - Subscribed to broadcast event: webhook.message - app.plugins.mediasyncdel.MediaSyncDel.sync_del_by_plugin
【DEBUG】2024-12-24 15:15:55,648 - event.py - Subscribed to broadcast event: webhook.message - app.plugins.mediasyncdel.MediaSyncDel.sync_del_by_webhook

**Comment by thsrite** [comment]
@qhly2010 ['.mp4', '.mkv', '.ts', '.iso',
                                 '.rmvb', '.avi', '.mov', '.mpeg',
                                 '.mpg', '.wmv', '.3gp', '.asf',
                                 '.m4v', '.flv', '.m2ts', '.strm',
                                 '.tp', '.f4v']

mp内置的视频格式， .FLAC显然不在这个范围之内，mp会判定为非媒体文件，然后删除文件夹

**Comment by qhly2010** [comment]
我现在的使用习惯是所有内容通过PTPP用qb下载到默认目录media，包括.rar、 .flac 、.exe等其他非媒体格式文件，当然也包括媒体内容，个人理解的删除源文件是如果下载了一个单独的视频文件Pegasus.2019.4K.WEB-DL.H264.AAC.mp4到media，就只删除Pegasus.2019.4K.WEB-DL.H264.AAC.mp4这个文件，而不删除其他数据包括media这个文件夹，如果下载的是下面这种含有文件夹的视频到media：
![原盘](https://github.com/user-attachments/assets/15648b88-b1c9-4986-afcc-399e0f6077c0)
那么删除的也只是Kill 2023 2160p GER UHD Blu-ray 这个文件夹，而不删除其他数据包括media这个文件夹。现有的删除逻辑好像是判断的有没有其他媒体文件，如果刚好meida这个文件没有其他的媒体文件，那么我的其他诸如.rar、.flac等文件会被全部删除（实际上已经被删除清空了）

如果这种删除逻辑做起来比较麻烦或者无法实现就不管了，我把这个删除源文件的功能给停止使用，辛苦你这几日的修改插件程序了，非常感谢！！

**Comment by thsrite** [comment]
@qhly2010 我还以为media下有媒体文件被误删了。
你这种场景也简单，再media下执行`touch .a.mp4`  创建个隐藏的空媒体文件即可
