### ISSUE TITLE
媒体文件同步删除 v1.9.0 异常

### ISSUE THREAD

**Issue by bonnyandsky** [thsrite/MoviePilot-Plugins#186]
MP版本：v2.1.6
emby版本：版本 [4.9.0.34] 测试版

历史记录路径显示和emby一样。我用的是硬链接
![image](https://github.com/user-attachments/assets/269f2e7e-9fd0-46e4-ac8b-03dd60e821c7)
![image](https://github.com/user-attachments/assets/cc735a51-4aa8-4eee-bf6a-82dd077f5bc1)

插件设置如下：（删除历史这个勾选上保存后再打开还是不勾选的状态）
![image](https://github.com/user-attachments/assets/65b83d63-0ed1-421b-ba09-345a15db3ee8)

这个是插件日志
![image](https://github.com/user-attachments/assets/3a9df2ad-7abb-439b-a0b7-d8ba5d9d5949)

我刚又试了下
前面日志报错的都是我之前手动下载，emby搜刮的数据。然后mp整理后重新推送给emby的片源（但是在MP整理的历史记录里是存在的，上面截图也看得出来。）
下面这个日志的片子是mp下载整理后搜刮数据，再推送给emby的，我emby删除就日志正常了，手机也能收到删除的推送消息。硬链接前后的文件也都被删除。但是奇怪的是tr里面做种的任务还能正常执行。这个时候删除的到底是源文件还是只是删除指针？
需要我手动删除做种任务，实际文件才会被删除？
忘记说了。系统是群晖dsm7.1.1的
tr 和mp都是docker部署的
![image](https://github.com/user-attachments/assets/df580176-60f0-4126-b33a-f4bce64af8ce)

这个删除记录的开关虽然显示异常，但是实际是起作用了，我看了下对应的记录也是被删除了。是不是和最新MP不兼容？

综上，有几个疑问
1：删除记录开关是否和最新mp不兼容，导致显示异常
2：硬链接前后的文件都被删除了，但是做种的任务还在。这个时候空间是否从磁盘里被释放出来？

**Comment by bonnyandsky** [comment]
我刚又试了下
前面日志报错的都是我之前手动下载，emby搜刮的数据。然后mp整理后重新推送给emby的片源（但是在MP整理的历史记录里是存在的，上面截图也看得出来。）
下面这个日志的片子是mp下载整理后搜刮数据，再推送给emby的，我emby删除就日志正常了，手机也能收到删除的推送消息。硬链接前后的文件也都被删除。但是奇怪的是tr里面做种的任务还能正常执行。这个时候删除的到底是源文件还是只是删除指针？
需要我手动删除做种任务，实际文件才会被删除？
忘记说了。系统是群晖dsm7.1.1的
tr 和mp都是docker部署的
![image](https://github.com/user-attachments/assets/df580176-60f0-4126-b33a-f4bce64af8ce)

**Comment by bonnyandsky** [comment]
这个删除记录的开关虽然显示异常，但是实际是起作用了，我看了下对应的记录也是被删除了。是不是和最新MP不兼容？

**Comment by thsrite** [comment]
@bonnyandsky 经过mp下载，转种辅种，整理，入库的文件被emby删除后，通知mp删除可以删干净，其他场景不支持

**Comment by bonnyandsky** [comment]
> 删除记录开关是否和最新mp不兼容，导致显示异常

删除记录开关是否和最新mp不兼容，导致显示异常

**Comment by bonnyandsky** [comment]
> @bonnyandsky 经过mp下载，转种辅种，整理，入库的文件被emby删除后，通知mp删除可以删干净，其他场景不支持

删除记录开关是否和最新mp不兼容，导致显示异常

**Comment by thsrite** [comment]
@bonnyandsky 测试无异常
