### ISSUE TITLE
需求: 能否加一个媒体库定时重命名的功能

### ISSUE THREAD

**Issue by dongjiqiang** [thsrite/MoviePilot-Plugins#22]
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/17396054/55e407fa-b8ca-40cb-9ad6-661a1536f2f6)
订阅的剧集整理完有时名称会没有, 就会显示成第*集, 能否新增一个插件, 按照重命名规则定时去改一下这个名字

**Comment by thsrite** [comment]
用媒体库刮削插件或者MediaServerTools
