### ISSUE TITLE
大佬 大佬 媒体文件同步插件问题

### ISSUE THREAD

**Issue by cng10001** [thsrite/MoviePilot-Plugins#26]
**配置是“日志同步”方式**
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/115156545/79be3f22-bd52-4001-a4aa-3fef05ed5ef9)
**问题是，当你调整了重命名格式，对mp历史记录重新整理，等到配置的检查时间会把重新整理的历史记录删除（媒体库文件没删）**
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/115156545/6c95a2f9-2213-4b85-8af8-5b9a2136db06)

![Snipaste_2024-03-15_08-57-04](https://github.com/thsrite/MoviePilot-Plugins/assets/115156545/f23eeb55-bb73-4523-bec5-072b9131ea29)

**Comment by thsrite** [comment]
用scripterx方式
