### ISSUE TITLE
生成alist云盘strm

### ISSUE THREAD

**Issue by LGuangming** [thsrite/MoviePilot-Plugins#27]
alist云盘如果有选择全部签名选项，除了文件本身alist连接外，还会生成签名信息 比如http://192.168.50.1:5222/d/阿里云盘/Movies/Deadly Sea (2023).1080p.mkv?sign=***jjjjjj=:0          但是目前好像云盘strm插件没有考虑签名选项

**Comment by Akimio521** [comment]
请问配置文件应该写，下面是我的一些信息：我alist的位置是`http://192.168.31.20:5244`，我想把alist路径中的`alidrive/movie`下的所有视频都生成strm文件存储到moviepilot容器内的`/downloads/strm/alidrive`中然后再用mp的刮削整理到我的媒体库中
