### ISSUE TITLE
插件仓库添加后插件市场无法获取插件

### ISSUE THREAD

**Issue by summer0607** [thsrite/MoviePilot-Plugins#3]
您好，非常荣幸能看到您的插件库，您对云盘strm文件的巧妙运用插件对我非常的有帮助，但是我在通过[MoviePilot]官方说明文档的帮助下，在app.env文件里修改了：PLUGIN_MARKET="https://raw.githubusercontent.com/jxxghp/MoviePilot](https://raw.githubusercontent.com/jxxghp/MoviePilot-Plugins/main/,https://github.com/thsrite/MoviePilot-Plugins/“配置，并重新启动MoviePilot容器，但是遗憾的是插件商场里并没有您的插件，于是我又进行了修改host、网络代理、将PLUGIN_MARKET单独设定为您的仓库地址，经过以上方法尝试均无法在插件商店找到您的插件，请问这是什么原因呢，我应该如何才能用上您的插件？
很期待您的解答！谢谢！

**Comment by thsrite** [comment]
仔细看下主仓库readme，你这明显写错了
