### ISSUE TITLE
两个插件依赖安装错误

### ISSUE THREAD

**Issue by autunn** [thsrite/MoviePilot-Plugins#30]
ERROR:   module.py - 加载模块 pushdeermsg 失败：No module named 'pypushdeer' - Tr
aceback (most recent call last):                                                 
  File "/app/app/helper/module.py", line 31, in load                             
    module = importlib.import_module(full_package_name)                          
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_mod
ule                                                                              
    return _bootstrap._gcd_import(name[level:], package, level)                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import                
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load             
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked    
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked              
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module        
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed   
  File "/app/app/plugins/pushdeermsg/__init__.py", line 3, in <module>           
    from pypushdeer import PushDeer                                              
ModuleNotFoundError: No module named 'pypushdeer'  

                                                                                 
ERROR:   module.py - 加载模块 vcbanimemonitor 失败：No module named 'roman' - Tra
ceback (most recent call last):                                                  
  File "/app/app/helper/module.py", line 31, in load                             
    module = importlib.import_module(full_package_name)                          
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                          
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_mod
ule                                                                              
    return _bootstrap._gcd_import(name[level:], package, level)                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import                
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load             
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked    
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked              
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module        
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed   
  File "/app/app/plugins/vcbanimemonitor/__init__.py", line 29, in <module>      
    from app.plugins.vcbanimemonitor.remeta import ReMeta                        
  File "/app/app/plugins/vcbanimemonitor/remeta.py", line 6, in <module>         
    import roman                                                                 

每次启动的时候，安装完插件就会报着两个错误，我之前在mp的issues提了bug，mp的作者说是插件问题，要么自己手动安装这两个插件依赖，要么不用插件，我常用的插件基本都是大佬你的，希望大佬看下这个问题

**Comment by thsrite** [comment]
谁写的去谁仓库提bug吧

**Comment by autunn** [comment]
> 谁写的去谁仓库提bug吧

我就两个插件仓库，一个你的，一个官方的。emmmm
