### ISSUE TITLE
EmbyReporter在微信上的推送好像有问题

### ISSUE THREAD

**Issue by NevermoreN** [thsrite/MoviePilot-Plugins#34]
EmbyReporter在微信上的推送好像有问题
显示不全 只能显示movie 显示不到tv

**Comment by autunn** [comment]
有个小建议，就是能不能把电影和电视分开推送，简单来说就是分两条消息推送，第一条是电影，第二条是电视剧，用户可以在插件中选择是否要同时推送这两个，或者单独推送某一个
