### ISSUE TITLE
云盘Strm生成

### ISSUE THREAD

**Issue by syscc** [thsrite/MoviePilot-Plugins#36]
有个想法不知道作者能不能加入一下，就是alist有api可以直接历遍alist文件，这样就可以不用挂载到本地，直接生成Strm
https://alist.nn.ci/zh/guide/api/fs.html#post-%E5%88%97%E5%87%BA%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95

**Comment by thsrite** [comment]
我不用alist，自己改下吧
---- 回复的原邮件 ----
发件人xiao ***@***.***>发送日期2024年04月11日 10:36 ***@***.***> ***@***.***>主题[thsrite/MoviePilot-Plugins] 云盘Strm生成 (Issue #36)
有个想法不知道作者能不能加入一下，就是alist有api可以直接历遍alist文件，这样就可以不用挂载到本地，直接生成Strm
https://alist.nn.ci/zh/guide/api/fs.html#post-%E5%88%97%E5%87%BA%E6%96%87%E4%BB%B6%E7%9B%AE%E5%BD%95

**Comment by syscc** [comment]
好的，了解了！
