### ISSUE TITLE
群晖webhook通知，发送测试消息失败

### ISSUE THREAD

**Issue by yangtao521** [thsrite/MoviePilot-Plugins#38]
192.168.0.110:34630 - "[1mGET /api/v1/plugin/SynologyNotify/webhook?text=%E6%82%A8%E7%9A%84%20YTLOVEZMY%E5%9C%A8%202024-04-17%20%E7%9A%84%2020%3A29%20%E5%8F%91%E7%94%9F%E4%BA%86%E6%96%B0%E7%9A%84%E7%B3%BB%E7%BB%9F%E4%BA%8B%E4%BB%B6%E3%80%82%0A%E6%9D%A5%E8%87%AA%20%20%E7%9A%84%E6%B5%8B%E8%AF%95%E6%B6%88%E6%81%AF HTTP/1.1[0m" [31m404 Not Found[0m

**Comment by thsrite** [comment]
重启下mp即可
