### ISSUE TITLE
自动签到 高清时间 失效

### ISSUE THREAD

**Issue by y403321959** [thsrite/MoviePilot-Plugins#39]
### 版本
v1.8.2
### 站点管理
测试 通过
浏览站点 可看到种子列表
### 版本
v1.9
### 配置：
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/35832654/64e3205f-7422-4f6f-ac5c-92a5dece6af8)
### 日志：
【INFO】2024-04-21 11:46:42,119 - autosignin - 高清时间 签到成功
【INFO】2024-04-21 11:46:41,423 - autosignin - 开始站点模拟登录：高清时间，地址：https://hdtime.org/...
## 站点：
高清时间
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/35832654/977cafc6-19fd-48a2-bac8-05c5515cf84d)

## 描述：
日志显示成功，实际却并没有签到成功。其他站点正常。

**Comment by thsrite** [comment]
没这问题
---- 回复的原邮件 ----
***@***.***>发送日期2024年04月21日 14:24 ***@***.***> ***@***.***>主题[thsrite/MoviePilot-Plugins] 自动签到 高清时间 失效。 (Issue #39)
mp 本体
版本
v1.8.2
站点管理
测试 通过
浏览站点 可看到种子列表
自动签到 插件
版本
v1.9
配置：
image.png (view on web)
日志：
【INFO】2024-04-21 11:46:42,119 - autosignin - 高清时间 签到成功
【INFO】2024-04-21 11:46:41,423 - autosignin - 开始站点模拟登录：高清时间，地址：https://hdtime.org/...
站点：
高清时间
image.png (view on web)
描述：
日志显示成功，实际却并没有签到成功。其他站点正常。

**Comment by y403321959** [comment]
感谢您的回复。
您那里正常是吗，那我如何排查能解决这个问题。

**Comment by thsrite** [comment]
站点管理加下获取ck的浏览器ua试试

**Comment by thsrite** [comment]
![IMG_8023](https://github.com/thsrite/MoviePilot-Plugins/assets/54088512/865078f8-634b-40dc-a892-71a134a99ed3)

**Comment by y403321959** [comment]
神医啊。我把浏览器ua删了就好了。感谢大佬。
