### ISSUE TITLE
strm生成似乎有问题

### ISSUE THREAD

**Issue by 1219099256** [thsrite/MoviePilot-Plugins#4]
配置为compatibility#/od/MOVIES#/EMBY#alist#/EMBY#ip:80
但是生成的strm内容为http://ip:80/d/od/MOVIES/外语电影/星际穿越 (2014)/星际穿越 (2014) - 1080p.mkv

如果我配置写的没问题的话应该是这样吧
http://ip:80/d/EMBY/外语电影/星际穿越 (2014)/星际穿越 (2014) - 1080p.mkv

**Comment by thsrite** [comment]
自己研究吧，没问题
