### ISSUE TITLE
插件安装报错403

### ISSUE THREAD

**Issue by jeffry88** [thsrite/MoviePilot-Plugins#40]
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/25890075/d1f755be-b974-46b1-9245-2b67ec29fdc4)
请问插件安装报403是啥原因啊

**Comment by jeffry88** [comment]
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/25890075/711ba993-fc88-4a7b-9c50-730242965965)
网络连通性正常

**Comment by thsrite** [comment]
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/54088512/d8444ef8-143f-4e13-a45c-a718af788754)
