### ISSUE TITLE
订阅填充插件

### ISSUE THREAD

**Issue by dlovew** [thsrite/MoviePilot-Plugins#41]
你好，大佬。今天看到你的订阅规则自动填充插件，添加个功能么，辛苦大佬考虑一下
监听到订阅事件，判断是不是动漫，如果是动漫给订阅指定站点、包含关键字、分辨率等信息

**Comment by thsrite** [comment]
你这名字有点熟悉，tg名是哪个？
---- 回复的原邮件 ----
***@***.***>发送日期2024年04月23日 19:54 ***@***.***> ***@***.***>主题[thsrite/MoviePilot-Plugins] 订阅填充插件 (Issue #41)
你好，大佬。今天看到你的订阅规则自动填充插件，添加个功能么，辛苦大佬考虑一下
监听到订阅事件，判断是不是动漫，如果是动漫给订阅指定站点、包含关键字、分辨率等信息

**Comment by dlovew** [comment]
> 你这名字有点熟悉，tg名是哪个？ ---- 回复的原邮件 ---- ***@***.***>发送日期2024年04月23日 19:54 ***@***.***> ***@***.***>主题[thsrite/MoviePilot-Plugins] 订阅填充插件 (Issue #41) 你好，大佬。今天看到你的订阅规则自动填充插件，添加个功能么，辛苦大佬考虑一下 监听到订阅事件，判断是不是动漫，如果是动漫给订阅指定站点、包含关键字、分辨率等信息 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

进nastools和mp群比较早，以前发言提issue多，现在不在群里说话了，tg是无名，头像是王也

**Comment by dlovew** [comment]
> 你这名字有点熟悉，tg名是哪个？ ---- 回复的原邮件 ---- ***@***.***>发送日期2024年04月23日 19:54 ***@***.***> ***@***.***>主题[thsrite/MoviePilot-Plugins] 订阅填充插件 (Issue #41) 你好，大佬。今天看到你的订阅规则自动填充插件，添加个功能么，辛苦大佬考虑一下 监听到订阅事件，判断是不是动漫，如果是动漫给订阅指定站点、包含关键字、分辨率等信息 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

好像我红叶还是你发的

**Comment by thsrite** [comment]
哦对，我说怎么这么熟悉

**Comment by dlovew** [comment]
大佬，感谢太牛了，这个功能解决我一直以来拉所有新番的痛点
我是这样配置的category:动漫#resolution:1080p#include:.*(CR.*简繁|简繁英).*RLWeb|ADWeb.*#sites:观众,红叶PT
但是运行的时候提示【ERROR】2024-04-23 21:43:54,711 - subscribegroup - 插件未开启二级分类自定义填充

**Comment by dlovew** [comment]
> 大佬，感谢太牛了，这个功能解决我一直以来拉所有新番的痛点 我是这样配置的category:动漫#resolution:1080p#include:.*(CR.*简繁|简繁英)._RLWeb|ADWeb._#sites:观众,红叶PT 但是运行的时候提示【ERROR】2024-04-23 21:43:54,711 - subscribegroup - 插件未开启二级分类自定义填充

这个正则我让gpt写的，不知道会不会影响插件开启

**Comment by dlovew** [comment]
> > > 大佬，感谢太牛了，这个功能解决我一直以来拉所有新番的痛点 我是这样配置的category:动漫#resolution:1080p#include:.*(CR.*简繁|简繁英)._RLWeb|ADWeb._#sites:观众,红叶PT 但是运行的时候提示【ERROR】2024-04-23 21:43:54,711 - subscribegroup - 插件未开启二级分类自定义填充
> > 
> > 
> > 这个正则我让gpt写的，不知道会不会影响插件开启
> 
> > 大佬，感谢太牛了，这个功能解决我一直以来拉所有新番的痛点 我是这样配置的category:动漫#resolution:1080p#include:.*(CR.*简繁|简繁英)._RLWeb|ADWeb._#sites:观众,红叶PT 但是运行的时候提示【ERROR】2024-04-23 21:43:54,711 - subscribegroup - 插件未开启二级分类自定义填充
> 
> 更新1.5，如果已经是的话，就用插件强制重装插件重装下

完美，happy，diao爆了👍👍👍

**Comment by thsrite** [comment]
> 我试了一下多行也可以，大佬可以写在提示里
> category:日番#include:.*(CR.*简繁|简繁英)._RLWeb|ADWeb._#sites:观众,红叶PT
> category:港台剧#include:国粤

是的，支持多行配置

**Comment by dlovew** [comment]
> > 我试了一下多行也可以，大佬可以写在提示里
> > category:日番#include:.*(CR.*简繁|简繁英)._RLWeb|ADWeb._#sites:观众,红叶PT
> > category:港台剧#include:国粤
> 
> 是的，支持多行配置

我发现这种模式特别友好，尤其是对于一些站点拥有比较有特色的资源，这个插件支持特定类型的剧集订阅特定站点，观众红叶的动漫，岛的港台剧等等，再次点赞
