### ISSUE TITLE
无法获取站内消息

### ISSUE THREAD

**Issue by tlsban** [thsrite/MoviePilot-Plugins#45]
![Uploading 1.png…]()

**Comment by tlsban** [comment]
![Uploading 屏幕截图 2024-05-03 234420.png…]()

**Comment by tlsban** [comment]
[https://vip.helloimg.com/i/2024/05/03/663508f782f48.png](url)

**Comment by tlsban** [comment]
https://vip.helloimg.com/i/2024/05/03/663508f782f48.png

**Comment by thsrite** [comment]
更新插件1.9
