### ISSUE TITLE
订阅规则自动填充插件报错

### ISSUE THREAD

**Issue by movieuu** [thsrite/MoviePilot-Plugins#46]
订阅规则自动填充插件-二级分类自动填充-include:包含关键
填写如下正则表达式 
(?:.*x265.*CMCT)|(?:.*x264.*CMCT)
则无法保存,docker日志中显示如下报错
ValueError: too many values to unpack (expected 2)

直接在订阅的包含关键词中填写上述正则表达式可以正常保存

**Comment by thsrite** [comment]
a0ffd5b41c9fe212df154c983f827a889140a499
