### ISSUE TITLE
云盘Strm生成 v4.2，失效

### ISSUE THREAD

**Issue by kingtalk** [thsrite/MoviePilot-Plugins#56]
定时运行，有新文件的情况下无法检测到新文件，无法生成strm文件。（15日还好用，17日开始就不好用了）
监控目录为：/CloudNAS/CloudDrive/alist/115/media
目的目录为：/media/cloud/strm
alist根目录为：/CloudNAS/CloudDrive/alist/
插件内设置为：/CloudNAS/CloudDrive/alist/115/media#/media/cloud/strm#alist#/CloudNAS/CloudDrive/alist/#域名:端口

同样情况下使用AutoSymlink可以生成strm。日志如下：

【INFO】2024-06-19 00:00:00,363 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-19 00:00:00,362 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-19 00:00:00,174 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-19 00:00:00,174 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-19 00:00:00,136 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-19 00:00:00,136 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-19 00:00:00,079 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-19 00:00:00,078 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-18 00:00:01,027 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-18 00:00:01,026 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-18 00:00:00,993 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-18 00:00:00,992 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-18 00:00:00,935 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-18 00:00:00,883 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-18 00:00:00,572 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-18 00:00:00,572 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-17 01:16:05,475 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-17 01:16:05,474 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-17 01:16:05,473 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-17 01:16:05,472 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-17 01:16:02,471 - cloudstrm - 云盘监控全量执行服务启动，立即运行一次
【INFO】2024-06-17 01:15:09,362 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-17 01:15:09,361 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-17 01:15:09,361 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-17 01:15:09,360 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-17 01:15:06,359 - cloudstrm - 云盘监控全量执行服务启动，立即运行一次

**Comment by thsrite** [comment]
插件设置，视频格式填上
.mp4, .mkv, .ts, .iso,.rmvb, .avi, .mov, .mpeg,.mpg, .wmv, .3gp, .asf, .m4v, .flv, .m2ts, .strm,.tp, .f4v
---- 回复的原邮件 ----
***@***.***>发送日期2024年6月19日 ***@***.***>***@***.***>主题[thsrite/MoviePilot-Plugins] 云盘Strm生成 v4.2，失效 (Issue #56)
定时运行，有新文件的情况下无法检测到新文件，无法生成strm文件。（15日还好用，17日开始就不好用了）
监控目录为：/CloudNAS/CloudDrive/alist/115/media
目的目录为：/media/cloud/strm
alist根目录为：/CloudNAS/CloudDrive/alist/
插件内设置为：/CloudNAS/CloudDrive/alist/115/media#/media/cloud/strm#alist#/CloudNAS/CloudDrive/alist/#域名:端口
同样情况下使用AutoSymlink可以生成strm。日志如下：
【INFO】2024-06-19 00:00:00,363 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-19 00:00:00,362 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-19 00:00:00,174 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-19 00:00:00,174 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-19 00:00:00,136 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-19 00:00:00,136 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-19 00:00:00,079 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-19 00:00:00,078 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-18 00:00:01,027 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-18 00:00:01,026 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-18 00:00:00,993 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-18 00:00:00,992 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-18 00:00:00,935 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-18 00:00:00,883 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-18 00:00:00,572 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-18 00:00:00,572 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-17 01:16:05,475 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-17 01:16:05,474 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-17 01:16:05,473 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-17 01:16:05,472 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-17 01:16:02,471 - cloudstrm - 云盘监控全量执行服务启动，立即运行一次
【INFO】2024-06-17 01:15:09,362 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-17 01:15:09,361 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-17 01:15:09,361 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-17 01:15:09,360 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-17 01:15:06,359 - cloudstrm - 云盘监控全量执行服务启动，立即运行一次

**Comment by kingtalk** [comment]
> .mp4, .mkv, .ts, .iso,.rmvb, .avi, .mov, .mpeg,.mpg, .wmv, .3gp, .asf, .m4v, .flv, .m2ts, .strm,.tp, .f4v

作者您好，之前就有视频格式。删除格式-保存-填写视频格式-保存-勾选立即运行-保存，还是没有反应。日志如下：

【INFO】2024-06-19 12:29:00,667 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-19 12:29:00,667 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-19 12:29:00,666 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-19 12:29:00,665 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-19 12:28:57,664 - cloudstrm - 云盘监控全量执行服务启动，立即运行一次

设置如下：
![WX20240619-123040@2x](https://github.com/thsrite/MoviePilot-Plugins/assets/100518445/811b2702-6208-4220-9daa-147d4fd81cd2)

**Comment by thsrite** [comment]
Mp容器里面能看到监控目录文件？是不是挂载掉了？3s结束，像是没获取到文件
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月19日 12:32 ***@***.***> ***@***.***>,
***@***.***>主题Re: [thsrite/MoviePilot-Plugins] 云盘Strm生成 v4.2，失效 (Issue #56)
.mp4, .mkv, .ts, .iso,.rmvb, .avi, .mov, .mpeg,.mpg, .wmv, .3gp, .asf, .m4v, .flv, .m2ts, .strm,.tp, .f4v
作者您好，之前就有视频格式。删除格式-保存-填写视频格式-保存-勾选立即运行-保存，还是没有反应。日志如下：
【INFO】2024-06-19 12:29:00,667 - cloudstrm - 云盘strm生成任务完成
【INFO】2024-06-19 12:29:00,667 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media
【INFO】2024-06-19 12:29:00,666 - cloudstrm - 尝试加载本地缓存
【INFO】2024-06-19 12:29:00,665 - cloudstrm - 云盘strm生成任务开始
【INFO】2024-06-19 12:28:57,664 - cloudstrm - 云盘监控全量执行服务启动，立即运行一次
设置如下：
***@***.*** (view on web)

**Comment by kingtalk** [comment]
> Mp容器里面能看到监控目录文件？是不是挂载掉了？3s结束，像是没获取到文件 ---- 回复的原邮件 ---- ***@***.***>发送日期2024年06月19日 12:32 ***@***.***> ***@***.***>, ***@***.***>主题Re: [thsrite/MoviePilot-Plugins] 云盘Strm生成 v4.2，失效 (Issue #56) .mp4, .mkv, .ts, .iso,.rmvb, .avi, .mov, .mpeg,.mpg, .wmv, .3gp, .asf, .m4v, .flv, .m2ts, .strm,.tp, .f4v 作者您好，之前就有视频格式。删除格式-保存-填写视频格式-保存-勾选立即运行-保存，还是没有反应。日志如下： 【INFO】2024-06-19 12:29:00,667 - cloudstrm - 云盘strm生成任务完成 【INFO】2024-06-19 12:29:00,667 - cloudstrm - 正在处理监控文件 /CloudNAS/CloudDrive/alist/115/media 【INFO】2024-06-19 12:29:00,666 - cloudstrm - 尝试加载本地缓存 【INFO】2024-06-19 12:29:00,665 - cloudstrm - 云盘strm生成任务开始 【INFO】2024-06-19 12:28:57,664 - cloudstrm - 云盘监控全量执行服务启动，立即运行一次 设置如下： ***@***.*** (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

对不起，作者大佬，我猪脑子，忘记映射CloudNAS了
