### ISSUE TITLE
是否考虑出一个CD2状态监控工具

### ISSUE THREAD

**Issue by saarjoye** [thsrite/MoviePilot-Plugins#57]
CD2挂载网盘时会掉盘，大佬是否考虑出一个状态监控的插件呀

**Comment by thsrite** [comment]
了解下docker挂载时shared slave属性
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月19日 14:39 ***@***.***> ***@***.***>主题[thsrite/MoviePilot-Plugins] 是否考虑出一个CD2状态监控工具 (Issue #57)
CD2挂载网盘时会掉盘，大佬是否考虑出一个状态监控的插件呀

**Comment by thsrite** [comment]
![Uploading image.png…]()

**Comment by thsrite** [comment]
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/54088512/428d72c1-bcbd-4297-9b7b-791a323d960c)
