### ISSUE TITLE
一有新文件入库，系统通知就会发两条错误信息

### ISSUE THREAD

**Issue by behinder85** [thsrite/MoviePilot-Plugins#58]
![image](https://github.com/InfinityPacer/MoviePilot-Plugins/assets/60542924/446f2b39-e7a1-433b-ba76-070ebbfd4ac8)

不知是何原因

使用了大佬的目录监控插件
MP版本V1.9.6

**Comment by thsrite** [comment]
去对应插件作者仓库提issues
---- 回复的原邮件 ----
***@***.***>发送日期2024年06月19日 18:26 ***@***.***> ***@***.***>主题[thsrite/MoviePilot-Plugins] 一有新文件入库，系统通知就会发两条错误信息 (Issue #58)
image.png (view on web)
不知是何原因
插件版本V1.0
MP版本V1.9.6
