### ISSUE TITLE
“媒体库重复媒体检测”插件疑惑

### ISSUE THREAD

**Issue by behinder85** [thsrite/MoviePilot-Plugins#62]
本地媒体库文件
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/60542924/017fb5e6-569d-4021-9943-568a0815299d)

日志
> 【WARNING】2024-06-29 22:37:34,320 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E05 - 第 5 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,317 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E05 - 第 5 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,315 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E05 - 第 5 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,313 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E05 - 第 5 集.* 2个
【WARNING】2024-06-29 22:37:34,303 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E05 - 第 5 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,300 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E05 - 第 5 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,297 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E05 - 第 5 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,295 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E05 - 第 5 集.* 2个
【WARNING】2024-06-29 22:37:34,285 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E05 - 第 5 集-thumb.jpg 将被删除
【INFO】2024-06-29 22:37:34,283 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E05 - 第 5 集-thumb.* 1个
【WARNING】2024-06-29 22:37:34,273 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E04 - 第 4 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,270 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E04 - 第 4 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,267 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E04 - 第 4 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,265 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E04 - 第 4 集.* 2个
【WARNING】2024-06-29 22:37:34,255 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E04 - 第 4 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,251 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E04 - 第 4 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,249 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E04 - 第 4 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,247 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E04 - 第 4 集.* 2个
【WARNING】2024-06-29 22:37:34,235 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E04 - 第 4 集-thumb.jpg 将被删除
【INFO】2024-06-29 22:37:34,232 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E04 - 第 4 集-thumb.* 1个
【WARNING】2024-06-29 22:37:34,222 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E03 - 第 3 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,219 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E03 - 第 3 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,217 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E03 - 第 3 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,214 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E03 - 第 3 集.* 2个
【WARNING】2024-06-29 22:37:34,204 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E03 - 第 3 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,201 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E03 - 第 3 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,198 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E03 - 第 3 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,196 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E03 - 第 3 集.* 2个
【WARNING】2024-06-29 22:37:34,185 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E03 - 第 3 集-thumb.jpg 将被删除
【INFO】2024-06-29 22:37:34,182 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E03 - 第 3 集-thumb.* 1个
【WARNING】2024-06-29 22:37:34,170 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E02 - 第 2 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,167 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E02 - 第 2 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,164 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E02 - 第 2 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,162 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E02 - 第 2 集.* 2个
【WARNING】2024-06-29 22:37:34,149 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E02 - 第 2 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,145 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E02 - 第 2 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,142 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E02 - 第 2 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,139 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E02 - 第 2 集.* 2个
【WARNING】2024-06-29 22:37:34,127 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E02 - 第 2 集-thumb.jpg 将被删除
【INFO】2024-06-29 22:37:34,110 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E02 - 第 2 集-thumb.* 1个
【WARNING】2024-06-29 22:37:34,097 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E01 - 第 1 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,093 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E01 - 第 1 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,090 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E01 - 第 1 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,087 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E01 - 第 1 集.* 2个
【WARNING】2024-06-29 22:37:34,076 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E01 - 第 1 集-thumb.jpg 将被删除
【WARNING】2024-06-29 22:37:34,072 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E01 - 第 1 集.nfo 将被删除
【WARNING】2024-06-29 22:37:34,070 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E01 - 第 1 集.mkv 将被删除
【INFO】2024-06-29 22:37:34,067 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E01 - 第 1 集.* 2个
【WARNING】2024-06-29 22:37:34,054 - libraryduplicatecheck - 监控文件 /Z/media/纪录片/王朝 (2018)/Season 1/王朝 - S01E01 - 第 1 集-thumb.jpg 将被删除
【INFO】2024-06-29 22:37:34,052 - libraryduplicatecheck - 筛选 /Z/media/纪录片/王朝 (2018)/Season 1 下同名文件 王朝 - S01E01 - 第 1 集-thumb.* 1个

本地媒体库文件是由MP硬链接得到的，但用大佬的插件检查之后绝大部分文件都存在重复，不知是何原因

附上MP插件设置截图
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/60542924/ff287b33-a3d7-4f99-a1da-29e675d3dd99)

**Comment by thsrite** [comment]
插件的目的是检测云盘、软连接之类
