### ISSUE TITLE
下载器文件同步插件不删除下载器里的任务什么情况

### ISSUE THREAD

**Issue by 389377616** [thsrite/MoviePilot-Plugins#63]
这个插件的作用不就是下载好的文件被删除以后，插件就会自动同步删除下载器里的任务嘛，我下载好的文件手动删除了，等了十几个小时，下载器里的任务还没有被删除，下载器是transmission

**Comment by thsrite** [comment]
并不是

**Comment by 389377616** [comment]
> 并不是

那这个插件是可以起到什么作用的呢😅
