### ISSUE TITLE
云盘strm生成(增量版)bug

### ISSUE THREAD

**Issue by Mruser0** [thsrite/MoviePilot-Plugins#72]
配置和日志如下，正常处理了三个视频后卡住不动了

![Screenshot_2024-07-26-12-18-03-08_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/6a6a4a86-813d-438e-83d7-d33602ec0b80)
![Screenshot_2024-07-26-12-18-21-16_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/faf552e7-0295-485f-9703-4cce842a6562)

**Comment by thsrite** [comment]
卡主的时候  mp容器应该有报错日志吧

**Comment by EliseFromNight** [comment]
> 卡主的时候 mp容器应该有报错日志吧

大佬我也是卡在扫描到增量文件就没反应了，是插件的问题吗？后面MP报错了，好像是权限的问题，但是我目录应该没问题才对，我云盘strm插件就能正常使用，然后这个增量版加了一个增量目录就卡在扫描到增量文件，正在处理........

**Comment by thsrite** [comment]
> > 卡主的时候 mp容器应该有报错日志吧
> 
> 大佬我也是卡在扫描到增量文件就没反应了，是插件的问题吗？后面MP报错了，好像是权限的问题，但是我目录应该没问题才对，我云盘strm插件就能正常使用，然后这个增量版加了一个增量目录就卡在扫描到增量文件，正在处理........

报错了  你把错误发上来

**Comment by EliseFromNight** [comment]
> > > 卡主的时候 mp容器应该有报错日志吧
> > 
> > 
> > 大佬我也是卡在扫描到增量文件就没反应了，是插件的问题吗？后面MP报错了，好像是权限的问题，但是我目录应该没问题才对，我云盘strm插件就能正常使用，然后这个增量版加了一个增量目录就卡在扫描到增量文件，正在处理........
> 
> 报错了 你把错误发上来

![微信截图_20240901000029](https://github.com/user-attachments/assets/f0cc2e42-584d-4276-aa59-3df5cf54144a)
这几天他不报错，每次扫描到就没后文了，有解决方法吗大佬

**Comment by thsrite** [comment]
试试云盘strm助手插件，比这个好用的。
