### ISSUE TITLE
SQL执行器没有反应 删除操作

### ISSUE THREAD

**Issue by 907739769** [thsrite/MoviePilot-Plugins#73]
如下 没有反应 数据没有删除
【INFO】2024-07-26 12:40:43,016 - sqlexecute - 
【INFO】2024-07-26 12:40:42,858 - sqlexecute - 开始执行SQL语句 delete from subscribe where id=122

**Comment by 907739769** [comment]
【INFO】2024-07-26 13:57:22,536 - sqlexecute - {"id": 122, "name": "", "year": "", "type": "", "keyword": "", "tmdbid": 0, "imdbid": "tt27589902", "tvdbid": None, "doubanid": None, "bangumiid": None, "season": None, "poster": "https://image.tmdb.org/t/p/w500/2eLjgesRLYQ8kjfwusSwxgNFcHv.jpg", "backdrop": "https://image.tmdb.org/t/p/w500/75Rnm6TSSgz0El8knofbVNzXDP4.jpg", "vote": 0.0, "description": "考古专家陈教授（成龙 饰）察觉，学生在冰川考察时发现的文物上的纹理和自己梦中所见到的一块玉佩极为相似，仿佛通过玉佩将梦境和现实联通了起来。带着所有的疑问，陈教授率领考察队深入冰川神庙，探寻梦中真相，共同开启一场奇幻冒险之旅。", "filter": None, "include": "", "exclude": "", "quality": "", "resolution": "", "effect": "", "total_episode": 0, "start_episode": 0, "lack_episode": None, "note": None, "state": "", "last_update": "", "date": "", "username": "", "sites": "[]", "best_version": 1, "current_priority": 0, "save_path": None, "search_imdbid": 1, "manual_total_episode": 1}
【INFO】2024-07-26 13:57:21,844 - sqlexecute - 开始执行SQL语句 select * from subscribe where id=122;
【INFO】2024-07-26 12:40:43,016 - sqlexecute - 
【INFO】2024-07-26 12:40:42,858 - sqlexecute - 开始执行SQL语句 delete from subscribe where id=122

**Comment by 907739769** [comment]
数据没有删除

**Comment by thsrite** [comment]
ed0556f3bcbbc5ba367dbf141f52e86566c417eb
