### ISSUE TITLE
请问下文件复制插件为什么执行了之后，目的目录还是空的？

### ISSUE THREAD

**Issue by EliseFromNight** [thsrite/MoviePilot-Plugins#75]
配置目录应该也没错呀？
![image](https://github.com/user-attachments/assets/bce942cb-7ef4-43b5-9c07-fc5ae09fa41e)

![image](https://github.com/user-attachments/assets/efb8ed93-43c0-4b1b-9742-74d5ded11d61)

**Comment by thsrite** [comment]
升级插件1.1  再运行看看日志
