### ISSUE TITLE
云盘strm生成 v4.4

### ISSUE THREAD

**Issue by pattonbina** [thsrite/MoviePilot-Plugins#78]
前一天运行正常
到当天后半夜插件日志开始出现
【INFO】2024-08-14 00:44:24,561 - cloudstrm - 尝试加载本地缓存
【INFO】2024-08-14 00:44:24,560 - cloudstrm - 云盘strm生成任务开始

查看mp日志

ERROR:   scheduler.py - 定时任务 云盘strm文件生成服务 执行失败：Invalid control character at: line 1 column 3489793 (char 3489792) - Traceback (most recent call last):
  File "/app/app/scheduler.py", line 374, in start
    job["func"](*args, **kwargs)
  File "/app/app/plugins/cloudstrm/__init__.py", line 204, in scan
    self.__cloud_files = json.loads(content)
                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid control character at: line 1 column 3489793 (char 3489792)

**Comment by pattonbina** [comment]
经查看config/plugins/CloudStrm/cloud.file.json文件中，存在大量的NULL，不知道是什么原因引起的，确实是跑着跑着故障了，我将json文件删除后，重新启动插件，可以正常运行了

**Comment by thsrite** [comment]
是不是你/mrgx路径下面有个文件的文件名有问题。
这个json文件存的是已有文件的文件路径。不会凭空产生的

**Comment by pattonbina** [comment]
应该没问题，把这个json删除之后我全量再跑了一遍，没有出现问题，可能是其他原因吧，算是已经解决了，之所以没关issue是想着这个问题可能对你优化程序有帮助，谢谢你的答复
![image](https://github.com/user-attachments/assets/bb6ac0c8-a4b0-4b47-be90-1aaba1c4ac78)
