### ISSUE TITLE
homepage 插件接口中的api_key如何获取

### ISSUE THREAD

**Issue by TMTBO** [thsrite/MoviePilot-Plugins#79]
请求一下, url: http://MoviePilot_IP:NGINX_PORT/api/v1/plugin/HomePage/statistic?apikey=api_token 这个接口中的apikey字段的值应该如何获取呀, 在moviepilot 中的设定中没有找到, homepage 插件中也没有找到

**Comment by thsrite** [comment]
https://wiki.movie-pilot.org/zh/configuration

**Comment by TMTBO** [comment]
谢谢
