### ISSUE TITLE
docker自定义任务插件保存报错

### ISSUE THREAD

**Issue by dongjiqiang** [thsrite/MoviePilot-Plugins#80]
![微信截图_20240816084923](https://github.com/user-attachments/assets/ddf650f9-3e1f-4522-b94e-b1b05a73f0e2)
大佬能否看一下这个, 保存时报错

**Comment by thsrite** [comment]
提供下日志

dongjiqiang ***@***.***> 于2024年8月16日周五 08:51写道：

**Comment by dongjiqiang** [comment]
![image](https://github.com/user-attachments/assets/ebb0eaa3-2723-4da1-a578-34b751e16305)
日志文件不存在, 是不是没保存上就没有

**Comment by thsrite** [comment]
你保存的时候看Moviepilot日志，不是插件日志
---- 回复的原邮件 ----
***@***.***>发送日期2024年08月18日 19:53 ***@***.***> ***@***.***>,
***@***.***>主题Re: [thsrite/MoviePilot-Plugins] docker自定义任务插件保存报错 (Issue #80)
image.png (view on web)
日志文件不存在, 是不是没保存上就没有

**Comment by dongjiqiang** [comment]
也同样没有日志

**Comment by thsrite** [comment]
![image](https://github.com/user-attachments/assets/6552c94b-6a66-48b7-8b23-d9ce4fb41805)
![image](https://github.com/user-attachments/assets/70bded62-6422-481b-aa2b-1f5231d8429d)
qbittorrent-4.3.9#0 6 * * *#restart
没问题  复现不出来你的问题

**Comment by dongjiqiang** [comment]
那就算了吧, 感谢大佬回复
