### ISSUE TITLE
云盘Strm生成 多一个‘/’？

### ISSUE THREAD

**Issue by xianglongwei** [thsrite/MoviePilot-Plugins#83]
云盘Strm生成 v4.4
配置如下
![image](https://github.com/user-attachments/assets/3f83b933-fba3-4705-ac30-dd524f51141b)
生成路径如下：
![image](https://github.com/user-attachments/assets/a9b862c6-9f97-4afb-8dc6-ea4d7a777783)
问题；
生成路径是否多了一个/？
![image](https://github.com/user-attachments/assets/35b72a37-6f2a-4763-bdb2-dfeac4f033ba)

配置文件，我尝试过
/115/link/movie#/mnt/user/nas/emby/movie#alist#/115/link/movie#192.168.10.5:5244
但是生成的文件是没有这个路径115/link/movie，当时没有截取日志。

**Comment by LegendAdmin** [comment]
改成`/115/link/movie#/mnt/user/nas/emby/movie#alist#/115/link/movie/#192.168.10.5:5244`

**Comment by xianglongwei** [comment]
没有用，生成的文件直接没有/115/link/movie/这一截路径

**Comment by xheia** [comment]
相同的问题，多一个‘/’，整一晚上，搞不定了。云盘Strm生成 v4.4
/media/Public/CloudDrive/WebDAV/MYDAV/115/115分享#/media/Public/strm_link/WebDAV/MYDAV/115/115分享#alist#/media/Public/WebDAV/MYDAV/115/115分享#192.168.3.96:5244


http://192.168.3.96:5244/d/%2Fmedia%2FPublic%2FCloudDrive%2FWebDAV%2FMYDAV%2F115%2F115%E5%88%86%E4%BA%AB%2F%E5%A5%B3%E6%B3%95%E5%8C%BBJD%20%282022%29%2FForensic.JD.S01.2022.2160p.WEB-DL.H265.AAC.2Audio-BlackTV%2FForensic.JD.S01E12.2022.2160p.WEB-DL.H265.AAC.2Audio-BlackTV.mkv
解码后URL:(D后面多了个‘/’)
http://192.168.3.96:5244/d//media/Public/CloudDrive/WebDAV/MYDAV/115/115分享/女法医JD (2022)/Forensic.JD.S01.2022.2160p.WEB-DL.H265.AAC.2Audio-BlackTV/Forensic.JD.S01E12.2022.2160p.WEB-DL.H265.AAC.2Audio-BlackTV.mkv
