### ISSUE TITLE
微信消息转发配置

### ISSUE THREAD

**Issue by xxtyyq** [thsrite/MoviePilot-Plugins#88]
您好大神，特别想用这个微信消息转发插件，但是小白一个，看了半天插件配置说明和设置微信配置里的模板，还是没太弄明白应该怎么配置。。。可否有个更详细的？或者类似填好的例子？我想配置一个单独的自建应用发送订阅消息和入库消息，谢谢！万分感谢

**Comment by thsrite** [comment]
![image](https://github.com/user-attachments/assets/47fc5309-73aa-4291-9587-8b8bb9593a9b)
设置微信配置   首次打开应该有默认配置

[
        {
            "remark": "入库消息",
            "appid": 1000001,
            "corpid": "",
            "appsecret": "",
            "pattern": "已入库",
            "extra_confs": [

            ],
        },
        {
            "remark": "站点签到数据统计",
            "appid": 1000002,
            "corpid": "",
            "appsecret": "",
            "pattern": "自动签到|自动登录|数据统计|刷流任务",
            "extra_confs": []
        }
    ]

**Comment by glovanni** [comment]
extra_confs参数是起什么作用？
