### ISSUE TITLE
大佬，大佬，媒体库文件删除插件相关问题

### ISSUE THREAD

**Issue by cng10001** [thsrite/MoviePilot-Plugins#9]
情况是这样的，小结一下：
同一个视频在A盘B盘各有一份，
用moviepilot在A盘硬链接到A盘，B盘硬链接到B盘
emby账户甲添加了A盘的硬链接文件夹，账户乙添加了B盘的硬链接文件夹，这种情况下，当你在账户甲删除那个文件的时候，插件会联动把A盘内的原始文件和硬链接文件也删除，但在B盘内，也会删除了原始文件，没有删除硬链接文件，而moviepilot里的历史记录又都删除的。

是不是会有这种情况，
其实最好是如果删除emby甲账户里的文件，不影响到moviepilot里另外一份B盘相关的历史记录和emby乙账户的文件。
![image](https://github.com/thsrite/MoviePilot-Plugins/assets/115156545/a46a8055-c575-49d7-aba9-99925d26aec2)

**Comment by thsrite** [comment]
源文件是同一份啊。那你不删除源文件好了，等自己清理
