### ISSUE TITLE
媒体库重复检测插件会将部分剧集识别成电影

### ISSUE THREAD

**Issue by samir2015dzh** [thsrite/MoviePilot-Plugins#96]
rt，例如
![image](https://github.com/user-attachments/assets/aa52cdba-b6be-4437-accd-af09c1c58c15)
![image](https://github.com/user-attachments/assets/5d16126b-2ac4-422b-b5ec-04445119a58b)
实际去看文件夹里面是没有重复媒体的，但是好像被错误识别成了电影，导致如果开了删除重复媒体的话，会把整个剧集删到只剩一集，海贼王，生活大爆炸，火影忍者等剧集都会这样，但是又有部分剧集例如家有儿女、抓马侦探啥都可以正确识别
![image](https://github.com/user-attachments/assets/4695ff34-c032-41b1-85d4-1a7303809b62)

**Comment by thsrite** [comment]
插件检查路径每一行末尾添加，插件说明有写
%电影
%电视剧
<img width="948" alt="image" src="https://github.com/user-attachments/assets/e3479793-5eb6-459a-8d24-401182564d3a">
